/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudGovernanceApi);
  }
}(this, function(expect, CloudGovernanceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudGovernanceApi.ApiMyGroup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiMyGroup', function() {
    it('should create an instance of ApiMyGroup', function() {
      // uncomment below and update the code to test ApiMyGroup
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be.a(CloudGovernanceApi.ApiMyGroup);
    });

    it('should have the property objectId (base name: "objectId")', function() {
      // uncomment below and update the code to test the property objectId
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property policyId (base name: "policyId")', function() {
      // uncomment below and update the code to test the property policyId
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property groupName (base name: "groupName")', function() {
      // uncomment below and update the code to test the property groupName
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property applyPolicyStatus (base name: "applyPolicyStatus")', function() {
      // uncomment below and update the code to test the property applyPolicyStatus
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property enableTeamCollaboration (base name: "enableTeamCollaboration")', function() {
      // uncomment below and update the code to test the property enableTeamCollaboration
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property groupType (base name: "groupType")', function() {
      // uncomment below and update the code to test the property groupType
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property createdTime (base name: "createdTime")', function() {
      // uncomment below and update the code to test the property createdTime
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property owners (base name: "owners")', function() {
      // uncomment below and update the code to test the property owners
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property preferredDataLocation (base name: "preferredDataLocation")', function() {
      // uncomment below and update the code to test the property preferredDataLocation
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property preferredDataLocationName (base name: "preferredDataLocationName")', function() {
      // uncomment below and update the code to test the property preferredDataLocationName
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property phase (base name: "phase")', function() {
      // uncomment below and update the code to test the property phase
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property phaseStartTime (base name: "phaseStartTime")', function() {
      // uncomment below and update the code to test the property phaseStartTime
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property phaseDescription (base name: "phaseDescription")', function() {
      // uncomment below and update the code to test the property phaseDescription
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property autoImportProfileId (base name: "autoImportProfileId")', function() {
      // uncomment below and update the code to test the property autoImportProfileId
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property autoImportProfileName (base name: "autoImportProfileName")', function() {
      // uncomment below and update the code to test the property autoImportProfileName
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property policyName (base name: "policyName")', function() {
      // uncomment below and update the code to test the property policyName
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property policyDescription (base name: "policyDescription")', function() {
      // uncomment below and update the code to test the property policyDescription
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property isCurrentRenewer (base name: "isCurrentRenewer")', function() {
      // uncomment below and update the code to test the property isCurrentRenewer
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property phaseAssignees (base name: "phaseAssignees")', function() {
      // uncomment below and update the code to test the property phaseAssignees
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property metadatas (base name: "metadatas")', function() {
      // uncomment below and update the code to test the property metadatas
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property primaryContact (base name: "primaryContact")', function() {
      // uncomment below and update the code to test the property primaryContact
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

    it('should have the property secondaryContact (base name: "secondaryContact")', function() {
      // uncomment below and update the code to test the property secondaryContact
      //var instane = new CloudGovernanceApi.ApiMyGroup();
      //expect(instance).to.be();
    });

  });

}));
