/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudGovernanceApi);
  }
}(this, function(expect, CloudGovernanceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudGovernanceApi.ChangeGroupSettingRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChangeGroupSettingRequest', function() {
    it('should create an instance of ChangeGroupSettingRequest', function() {
      // uncomment below and update the code to test ChangeGroupSettingRequest
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be.a(CloudGovernanceApi.ChangeGroupSettingRequest);
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupEmail (base name: "groupEmail")', function() {
      // uncomment below and update the code to test the property groupEmail
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupName (base name: "groupName")', function() {
      // uncomment below and update the code to test the property groupName
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalGroupName (base name: "originalGroupName")', function() {
      // uncomment below and update the code to test the property originalGroupName
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupDescription (base name: "groupDescription")', function() {
      // uncomment below and update the code to test the property groupDescription
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalGroupDescription (base name: "originalGroupDescription")', function() {
      // uncomment below and update the code to test the property originalGroupDescription
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property primaryContact (base name: "primaryContact")', function() {
      // uncomment below and update the code to test the property primaryContact
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalPrimaryContact (base name: "originalPrimaryContact")', function() {
      // uncomment below and update the code to test the property originalPrimaryContact
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property secondaryContact (base name: "secondaryContact")', function() {
      // uncomment below and update the code to test the property secondaryContact
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalSecondaryContact (base name: "originalSecondaryContact")', function() {
      // uncomment below and update the code to test the property originalSecondaryContact
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupOwners (base name: "groupOwners")', function() {
      // uncomment below and update the code to test the property groupOwners
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupMembers (base name: "groupMembers")', function() {
      // uncomment below and update the code to test the property groupMembers
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property isDynamicMembership (base name: "isDynamicMembership")', function() {
      // uncomment below and update the code to test the property isDynamicMembership
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property dynamicMembershipRules (base name: "dynamicMembershipRules")', function() {
      // uncomment below and update the code to test the property dynamicMembershipRules
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property enabledSubscribe (base name: "enabledSubscribe")', function() {
      // uncomment below and update the code to test the property enabledSubscribe
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalEnabledSubscribe (base name: "originalEnabledSubscribe")', function() {
      // uncomment below and update the code to test the property originalEnabledSubscribe
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property enabledOutsideSender (base name: "enabledOutsideSender")', function() {
      // uncomment below and update the code to test the property enabledOutsideSender
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalEnabledOutsideSender (base name: "originalEnabledOutsideSender")', function() {
      // uncomment below and update the code to test the property originalEnabledOutsideSender
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property hubSiteActionType (base name: "hubSiteActionType")', function() {
      // uncomment below and update the code to test the property hubSiteActionType
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property associateHubSiteId (base name: "associateHubSiteId")', function() {
      // uncomment below and update the code to test the property associateHubSiteId
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property associateHubSiteTitle (base name: "associateHubSiteTitle")', function() {
      // uncomment below and update the code to test the property associateHubSiteTitle
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property classification (base name: "classification")', function() {
      // uncomment below and update the code to test the property classification
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalClassification (base name: "originalClassification")', function() {
      // uncomment below and update the code to test the property originalClassification
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property enableTeams (base name: "enableTeams")', function() {
      // uncomment below and update the code to test the property enableTeams
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalEnableTeams (base name: "originalEnableTeams")', function() {
      // uncomment below and update the code to test the property originalEnableTeams
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property groupMetadatas (base name: "groupMetadatas")', function() {
      // uncomment below and update the code to test the property groupMetadatas
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalGroupMetadata (base name: "originalGroupMetadata")', function() {
      // uncomment below and update the code to test the property originalGroupMetadata
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property serviceId (base name: "serviceId")', function() {
      // uncomment below and update the code to test the property serviceId
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property department (base name: "department")', function() {
      // uncomment below and update the code to test the property department
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property notesToApprovers (base name: "notesToApprovers")', function() {
      // uncomment below and update the code to test the property notesToApprovers
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property questionnaireId (base name: "questionnaireId")', function() {
      // uncomment below and update the code to test the property questionnaireId
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property metadatas (base name: "metadatas")', function() {
      // uncomment below and update the code to test the property metadatas
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property ticketNumber (base name: "ticketNumber")', function() {
      // uncomment below and update the code to test the property ticketNumber
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property typeDescription (base name: "typeDescription")', function() {
      // uncomment below and update the code to test the property typeDescription
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property requester (base name: "requester")', function() {
      // uncomment below and update the code to test the property requester
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property progressStatus (base name: "progressStatus")', function() {
      // uncomment below and update the code to test the property progressStatus
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property progressStatusDescription (base name: "progressStatusDescription")', function() {
      // uncomment below and update the code to test the property progressStatusDescription
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property submittedTime (base name: "submittedTime")', function() {
      // uncomment below and update the code to test the property submittedTime
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "lastUpdated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property createdTime (base name: "createdTime")', function() {
      // uncomment below and update the code to test the property createdTime
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property assignTo (base name: "assignTo")', function() {
      // uncomment below and update the code to test the property assignTo
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

    it('should have the property fullPath (base name: "fullPath")', function() {
      // uncomment below and update the code to test the property fullPath
      //var instane = new CloudGovernanceApi.ChangeGroupSettingRequest();
      //expect(instance).to.be();
    });

  });

}));
