/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudGovernanceApi);
  }
}(this, function(expect, CloudGovernanceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudGovernanceApi.ChangePermissionValidateResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChangePermissionValidateResult', function() {
    it('should create an instance of ChangePermissionValidateResult', function() {
      // uncomment below and update the code to test ChangePermissionValidateResult
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be.a(CloudGovernanceApi.ChangePermissionValidateResult);
    });

    it('should have the property siteId (base name: "siteId")', function() {
      // uncomment below and update the code to test the property siteId
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property siteUrl (base name: "siteUrl")', function() {
      // uncomment below and update the code to test the property siteUrl
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property webId (base name: "webId")', function() {
      // uncomment below and update the code to test the property webId
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property webServerRelativeUrl (base name: "webServerRelativeUrl")', function() {
      // uncomment below and update the code to test the property webServerRelativeUrl
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property listTitle (base name: "listTitle")', function() {
      // uncomment below and update the code to test the property listTitle
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property objectUrl (base name: "objectUrl")', function() {
      // uncomment below and update the code to test the property objectUrl
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property isInherit (base name: "isInherit")', function() {
      // uncomment below and update the code to test the property isInherit
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property inheritNodeType (base name: "inheritNodeType")', function() {
      // uncomment below and update the code to test the property inheritNodeType
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property topInheritUrl (base name: "topInheritUrl")', function() {
      // uncomment below and update the code to test the property topInheritUrl
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property checkType (base name: "checkType")', function() {
      // uncomment below and update the code to test the property checkType
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property isValid (base name: "isValid")', function() {
      // uncomment below and update the code to test the property isValid
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new CloudGovernanceApi.ChangePermissionValidateResult();
      //expect(instance).to.be();
    });

  });

}));
