/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudGovernanceApi);
  }
}(this, function(expect, CloudGovernanceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudGovernanceApi.GroupValidationParameter();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GroupValidationParameter', function() {
    it('should create an instance of GroupValidationParameter', function() {
      // uncomment below and update the code to test GroupValidationParameter
      //var instane = new CloudGovernanceApi.GroupValidationParameter();
      //expect(instance).to.be.a(CloudGovernanceApi.GroupValidationParameter);
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new CloudGovernanceApi.GroupValidationParameter();
      //expect(instance).to.be();
    });

    it('should have the property groupEmail (base name: "groupEmail")', function() {
      // uncomment below and update the code to test the property groupEmail
      //var instane = new CloudGovernanceApi.GroupValidationParameter();
      //expect(instance).to.be();
    });

    it('should have the property isEditTask (base name: "isEditTask")', function() {
      // uncomment below and update the code to test the property isEditTask
      //var instane = new CloudGovernanceApi.GroupValidationParameter();
      //expect(instance).to.be();
    });

    it('should have the property isFromQuestionnaire (base name: "isFromQuestionnaire")', function() {
      // uncomment below and update the code to test the property isFromQuestionnaire
      //var instane = new CloudGovernanceApi.GroupValidationParameter();
      //expect(instance).to.be();
    });

  });

}));
