/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudGovernanceApi);
  }
}(this, function(expect, CloudGovernanceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudGovernanceApi.MembershipRenewalItemModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MembershipRenewalItemModel', function() {
    it('should create an instance of MembershipRenewalItemModel', function() {
      // uncomment below and update the code to test MembershipRenewalItemModel
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be.a(CloudGovernanceApi.MembershipRenewalItemModel);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property userDisplayName (base name: "userDisplayName")', function() {
      // uncomment below and update the code to test the property userDisplayName
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property groupUserType (base name: "groupUserType")', function() {
      // uncomment below and update the code to test the property groupUserType
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property groupUserTypeDescription (base name: "groupUserTypeDescription")', function() {
      // uncomment below and update the code to test the property groupUserTypeDescription
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property accessType (base name: "accessType")', function() {
      // uncomment below and update the code to test the property accessType
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property accessTypeDescription (base name: "accessTypeDescription")', function() {
      // uncomment below and update the code to test the property accessTypeDescription
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property objectId (base name: "objectId")', function() {
      // uncomment below and update the code to test the property objectId
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instane = new CloudGovernanceApi.MembershipRenewalItemModel();
      //expect(instance).to.be();
    });

  });

}));
