/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiUser model module.
 * @module model/ApiUser
 * @version 1.0
 */
class ApiUser {
    /**
     * Constructs a new <code>ApiUser</code>.
     * @alias module:model/ApiUser
     */
    constructor() { 
        
        ApiUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiUser} obj Optional instance to populate.
     * @return {module:model/ApiUser} The populated <code>ApiUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('loginName')) {
                obj['loginName'] = ApiClient.convertToType(data['loginName'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('isGroup')) {
                obj['isGroup'] = ApiClient.convertToType(data['isGroup'], 'Boolean');
            }
            if (data.hasOwnProperty('jobTitle')) {
                obj['jobTitle'] = ApiClient.convertToType(data['jobTitle'], 'String');
            }
            if (data.hasOwnProperty('physicalDeliveryOfficeName')) {
                obj['physicalDeliveryOfficeName'] = ApiClient.convertToType(data['physicalDeliveryOfficeName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ApiUser.prototype['id'] = undefined;

/**
 * @member {String} loginName
 */
ApiUser.prototype['loginName'] = undefined;

/**
 * @member {String} displayName
 */
ApiUser.prototype['displayName'] = undefined;

/**
 * @member {String} email
 */
ApiUser.prototype['email'] = undefined;

/**
 * @member {Boolean} isGroup
 */
ApiUser.prototype['isGroup'] = undefined;

/**
 * @member {String} jobTitle
 */
ApiUser.prototype['jobTitle'] = undefined;

/**
 * @member {String} physicalDeliveryOfficeName
 */
ApiUser.prototype['physicalDeliveryOfficeName'] = undefined;






export default ApiUser;

