/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChangeWebSPObject from './ChangeWebSPObject';
import RequestMetadata from './RequestMetadata';
import RequestMetadataListChangedProperty from './RequestMetadataListChangedProperty';
import RequestStatus from './RequestStatus';
import ServiceType from './ServiceType';
import StringChangedProperty from './StringChangedProperty';

/**
 * The ChangeWebSettingRequest model module.
 * @module model/ChangeWebSettingRequest
 * @version 1.0
 */
class ChangeWebSettingRequest {
    /**
     * Constructs a new <code>ChangeWebSettingRequest</code>.
     * @alias module:model/ChangeWebSettingRequest
     */
    constructor() { 
        
        ChangeWebSettingRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangeWebSettingRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeWebSettingRequest} obj Optional instance to populate.
     * @return {module:model/ChangeWebSettingRequest} The populated <code>ChangeWebSettingRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeWebSettingRequest();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ChangeWebSPObject.constructFromObject(data['url']);
            }
            if (data.hasOwnProperty('changedTitle')) {
                obj['changedTitle'] = StringChangedProperty.constructFromObject(data['changedTitle']);
            }
            if (data.hasOwnProperty('changedDescription')) {
                obj['changedDescription'] = StringChangedProperty.constructFromObject(data['changedDescription']);
            }
            if (data.hasOwnProperty('changedMetadata')) {
                obj['changedMetadata'] = RequestMetadataListChangedProperty.constructFromObject(data['changedMetadata']);
            }
            if (data.hasOwnProperty('deploymentPlanName')) {
                obj['deploymentPlanName'] = ApiClient.convertToType(data['deploymentPlanName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('notesToApprovers')) {
                obj['notesToApprovers'] = ApiClient.convertToType(data['notesToApprovers'], 'String');
            }
            if (data.hasOwnProperty('questionnaireId')) {
                obj['questionnaireId'] = ApiClient.convertToType(data['questionnaireId'], 'String');
            }
            if (data.hasOwnProperty('metadatas')) {
                obj['metadatas'] = ApiClient.convertToType(data['metadatas'], [RequestMetadata]);
            }
            if (data.hasOwnProperty('ticketNumber')) {
                obj['ticketNumber'] = ApiClient.convertToType(data['ticketNumber'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ServiceType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('typeDescription')) {
                obj['typeDescription'] = ApiClient.convertToType(data['typeDescription'], 'String');
            }
            if (data.hasOwnProperty('requester')) {
                obj['requester'] = ApiClient.convertToType(data['requester'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = RequestStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('progressStatus')) {
                obj['progressStatus'] = ApiClient.convertToType(data['progressStatus'], 'Number');
            }
            if (data.hasOwnProperty('progressStatusDescription')) {
                obj['progressStatusDescription'] = ApiClient.convertToType(data['progressStatusDescription'], 'String');
            }
            if (data.hasOwnProperty('submittedTime')) {
                obj['submittedTime'] = ApiClient.convertToType(data['submittedTime'], 'Date');
            }
            if (data.hasOwnProperty('lastUpdated')) {
                obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
            }
            if (data.hasOwnProperty('createdTime')) {
                obj['createdTime'] = ApiClient.convertToType(data['createdTime'], 'Date');
            }
            if (data.hasOwnProperty('assignTo')) {
                obj['assignTo'] = ApiClient.convertToType(data['assignTo'], 'String');
            }
            if (data.hasOwnProperty('fullPath')) {
                obj['fullPath'] = ApiClient.convertToType(data['fullPath'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ChangeWebSPObject} url
 */
ChangeWebSettingRequest.prototype['url'] = undefined;

/**
 * @member {module:model/StringChangedProperty} changedTitle
 */
ChangeWebSettingRequest.prototype['changedTitle'] = undefined;

/**
 * @member {module:model/StringChangedProperty} changedDescription
 */
ChangeWebSettingRequest.prototype['changedDescription'] = undefined;

/**
 * @member {module:model/RequestMetadataListChangedProperty} changedMetadata
 */
ChangeWebSettingRequest.prototype['changedMetadata'] = undefined;

/**
 * @member {String} deploymentPlanName
 */
ChangeWebSettingRequest.prototype['deploymentPlanName'] = undefined;

/**
 * @member {String} id
 */
ChangeWebSettingRequest.prototype['id'] = undefined;

/**
 * @member {String} serviceId
 */
ChangeWebSettingRequest.prototype['serviceId'] = undefined;

/**
 * @member {String} department
 */
ChangeWebSettingRequest.prototype['department'] = undefined;

/**
 * @member {String} summary
 */
ChangeWebSettingRequest.prototype['summary'] = undefined;

/**
 * @member {String} notesToApprovers
 */
ChangeWebSettingRequest.prototype['notesToApprovers'] = undefined;

/**
 * @member {String} questionnaireId
 */
ChangeWebSettingRequest.prototype['questionnaireId'] = undefined;

/**
 * @member {Array.<module:model/RequestMetadata>} metadatas
 */
ChangeWebSettingRequest.prototype['metadatas'] = undefined;

/**
 * @member {Number} ticketNumber
 */
ChangeWebSettingRequest.prototype['ticketNumber'] = undefined;

/**
 * @member {module:model/ServiceType} type
 */
ChangeWebSettingRequest.prototype['type'] = undefined;

/**
 * @member {String} typeDescription
 */
ChangeWebSettingRequest.prototype['typeDescription'] = undefined;

/**
 * @member {String} requester
 */
ChangeWebSettingRequest.prototype['requester'] = undefined;

/**
 * @member {module:model/RequestStatus} status
 */
ChangeWebSettingRequest.prototype['status'] = undefined;

/**
 * @member {Number} progressStatus
 */
ChangeWebSettingRequest.prototype['progressStatus'] = undefined;

/**
 * @member {String} progressStatusDescription
 */
ChangeWebSettingRequest.prototype['progressStatusDescription'] = undefined;

/**
 * @member {Date} submittedTime
 */
ChangeWebSettingRequest.prototype['submittedTime'] = undefined;

/**
 * @member {Date} lastUpdated
 */
ChangeWebSettingRequest.prototype['lastUpdated'] = undefined;

/**
 * @member {Date} createdTime
 */
ChangeWebSettingRequest.prototype['createdTime'] = undefined;

/**
 * @member {String} assignTo
 */
ChangeWebSettingRequest.prototype['assignTo'] = undefined;

/**
 * @member {String} fullPath
 */
ChangeWebSettingRequest.prototype['fullPath'] = undefined;






export default ChangeWebSettingRequest;

