/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiRequestProgressStatus from './ApiRequestProgressStatus';
import ApiUser from './ApiUser';
import ChangeContactByUrlSetting from './ChangeContactByUrlSetting';

/**
 * The ChangeSiteContactSubRequest model module.
 * @module model/ChangeSiteContactSubRequest
 * @version 1.0
 */
class ChangeSiteContactSubRequest {
    /**
     * Constructs a new <code>ChangeSiteContactSubRequest</code>.
     * @alias module:model/ChangeSiteContactSubRequest
     */
    constructor() { 
        
        ChangeSiteContactSubRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangeSiteContactSubRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeSiteContactSubRequest} obj Optional instance to populate.
     * @return {module:model/ChangeSiteContactSubRequest} The populated <code>ChangeSiteContactSubRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeSiteContactSubRequest();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('assignTo')) {
                obj['assignTo'] = ApiClient.convertToType(data['assignTo'], [ApiUser]);
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('statusDescription')) {
                obj['statusDescription'] = ApiClient.convertToType(data['statusDescription'], 'String');
            }
            if (data.hasOwnProperty('adminContactSettings')) {
                obj['adminContactSettings'] = ChangeContactByUrlSetting.constructFromObject(data['adminContactSettings']);
            }
            if (data.hasOwnProperty('progressStatus')) {
                obj['progressStatus'] = ApiRequestProgressStatus.constructFromObject(data['progressStatus']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ChangeSiteContactSubRequest.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/ApiUser>} assignTo
 */
ChangeSiteContactSubRequest.prototype['assignTo'] = undefined;

/**
 * @member {String} reason
 */
ChangeSiteContactSubRequest.prototype['reason'] = undefined;

/**
 * @member {Number} status
 */
ChangeSiteContactSubRequest.prototype['status'] = undefined;

/**
 * @member {String} statusDescription
 */
ChangeSiteContactSubRequest.prototype['statusDescription'] = undefined;

/**
 * @member {module:model/ChangeContactByUrlSetting} adminContactSettings
 */
ChangeSiteContactSubRequest.prototype['adminContactSettings'] = undefined;

/**
 * @member {module:model/ApiRequestProgressStatus} progressStatus
 */
ChangeSiteContactSubRequest.prototype['progressStatus'] = undefined;






export default ChangeSiteContactSubRequest;

