/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuidModel from './GuidModel';

/**
 * The ContentMoveProfileMappings model module.
 * @module model/ContentMoveProfileMappings
 * @version 1.0
 */
class ContentMoveProfileMappings {
    /**
     * Constructs a new <code>ContentMoveProfileMappings</code>.
     * @alias module:model/ContentMoveProfileMappings
     */
    constructor() { 
        
        ContentMoveProfileMappings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContentMoveProfileMappings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContentMoveProfileMappings} obj Optional instance to populate.
     * @return {module:model/ContentMoveProfileMappings} The populated <code>ContentMoveProfileMappings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentMoveProfileMappings();

            if (data.hasOwnProperty('columnMapping')) {
                obj['columnMapping'] = GuidModel.constructFromObject(data['columnMapping']);
            }
            if (data.hasOwnProperty('contentTypeMapping')) {
                obj['contentTypeMapping'] = GuidModel.constructFromObject(data['contentTypeMapping']);
            }
            if (data.hasOwnProperty('userMapping')) {
                obj['userMapping'] = GuidModel.constructFromObject(data['userMapping']);
            }
            if (data.hasOwnProperty('languageMapping')) {
                obj['languageMapping'] = GuidModel.constructFromObject(data['languageMapping']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GuidModel} columnMapping
 */
ContentMoveProfileMappings.prototype['columnMapping'] = undefined;

/**
 * @member {module:model/GuidModel} contentTypeMapping
 */
ContentMoveProfileMappings.prototype['contentTypeMapping'] = undefined;

/**
 * @member {module:model/GuidModel} userMapping
 */
ContentMoveProfileMappings.prototype['userMapping'] = undefined;

/**
 * @member {module:model/GuidModel} languageMapping
 */
ContentMoveProfileMappings.prototype['languageMapping'] = undefined;






export default ContentMoveProfileMappings;

