/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContructUrlSetting from './ContructUrlSetting';
import TextValidationRuleRef from './TextValidationRuleRef';

/**
 * The CreateListUrlSettings model module.
 * @module model/CreateListUrlSettings
 * @version 1.0
 */
class CreateListUrlSettings {
    /**
     * Constructs a new <code>CreateListUrlSettings</code>.
     * @alias module:model/CreateListUrlSettings
     */
    constructor() { 
        
        CreateListUrlSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateListUrlSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateListUrlSettings} obj Optional instance to populate.
     * @return {module:model/CreateListUrlSettings} The populated <code>CreateListUrlSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateListUrlSettings();

            if (data.hasOwnProperty('enableContructUrl')) {
                obj['enableContructUrl'] = ApiClient.convertToType(data['enableContructUrl'], 'Boolean');
            }
            if (data.hasOwnProperty('contructUrlSetting')) {
                obj['contructUrlSetting'] = ContructUrlSetting.constructFromObject(data['contructUrlSetting']);
            }
            if (data.hasOwnProperty('enableUrlValidation')) {
                obj['enableUrlValidation'] = ApiClient.convertToType(data['enableUrlValidation'], 'Boolean');
            }
            if (data.hasOwnProperty('textValidationRule')) {
                obj['textValidationRule'] = TextValidationRuleRef.constructFromObject(data['textValidationRule']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} enableContructUrl
 */
CreateListUrlSettings.prototype['enableContructUrl'] = undefined;

/**
 * @member {module:model/ContructUrlSetting} contructUrlSetting
 */
CreateListUrlSettings.prototype['contructUrlSetting'] = undefined;

/**
 * @member {Boolean} enableUrlValidation
 */
CreateListUrlSettings.prototype['enableUrlValidation'] = undefined;

/**
 * @member {module:model/TextValidationRuleRef} textValidationRule
 */
CreateListUrlSettings.prototype['textValidationRule'] = undefined;






export default CreateListUrlSettings;

