/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignBy from './AssignBy';

/**
 * The DpmServiceSetting model module.
 * @module model/DpmServiceSetting
 * @version 1.0
 */
class DpmServiceSetting {
    /**
     * Constructs a new <code>DpmServiceSetting</code>.
     * @alias module:model/DpmServiceSetting
     */
    constructor() { 
        
        DpmServiceSetting.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DpmServiceSetting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DpmServiceSetting} obj Optional instance to populate.
     * @return {module:model/DpmServiceSetting} The populated <code>DpmServiceSetting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DpmServiceSetting();

            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultValue')) {
                obj['defaultValue'] = ApiClient.convertToType(data['defaultValue'], 'String');
            }
            if (data.hasOwnProperty('selectedItems')) {
                obj['selectedItems'] = ApiClient.convertToType(data['selectedItems'], ['String']);
            }
            if (data.hasOwnProperty('assignBy')) {
                obj['assignBy'] = AssignBy.constructFromObject(data['assignBy']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isEnabled
 */
DpmServiceSetting.prototype['isEnabled'] = undefined;

/**
 * @member {String} defaultValue
 */
DpmServiceSetting.prototype['defaultValue'] = undefined;

/**
 * @member {Array.<String>} selectedItems
 */
DpmServiceSetting.prototype['selectedItems'] = undefined;

/**
 * @member {module:model/AssignBy} assignBy
 */
DpmServiceSetting.prototype['assignBy'] = undefined;






export default DpmServiceSetting;

