/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListValidationParameter model module.
 * @module model/ListValidationParameter
 * @version 1.0
 */
class ListValidationParameter {
    /**
     * Constructs a new <code>ListValidationParameter</code>.
     * @alias module:model/ListValidationParameter
     */
    constructor() { 
        
        ListValidationParameter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListValidationParameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListValidationParameter} obj Optional instance to populate.
     * @return {module:model/ListValidationParameter} The populated <code>ListValidationParameter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListValidationParameter();

            if (data.hasOwnProperty('listUrl')) {
                obj['listUrl'] = ApiClient.convertToType(data['listUrl'], 'String');
            }
            if (data.hasOwnProperty('parentUrl')) {
                obj['parentUrl'] = ApiClient.convertToType(data['parentUrl'], 'String');
            }
            if (data.hasOwnProperty('listTitle')) {
                obj['listTitle'] = ApiClient.convertToType(data['listTitle'], 'String');
            }
            if (data.hasOwnProperty('isDocumentLibrary')) {
                obj['isDocumentLibrary'] = ApiClient.convertToType(data['isDocumentLibrary'], 'Boolean');
            }
            if (data.hasOwnProperty('isEditTask')) {
                obj['isEditTask'] = ApiClient.convertToType(data['isEditTask'], 'Boolean');
            }
            if (data.hasOwnProperty('isFromQuestionnaire')) {
                obj['isFromQuestionnaire'] = ApiClient.convertToType(data['isFromQuestionnaire'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} listUrl
 */
ListValidationParameter.prototype['listUrl'] = undefined;

/**
 * @member {String} parentUrl
 */
ListValidationParameter.prototype['parentUrl'] = undefined;

/**
 * @member {String} listTitle
 */
ListValidationParameter.prototype['listTitle'] = undefined;

/**
 * @member {Boolean} isDocumentLibrary
 */
ListValidationParameter.prototype['isDocumentLibrary'] = undefined;

/**
 * @member {Boolean} isEditTask
 */
ListValidationParameter.prototype['isEditTask'] = undefined;

/**
 * @member {Boolean} isFromQuestionnaire
 */
ListValidationParameter.prototype['isFromQuestionnaire'] = undefined;






export default ListValidationParameter;

