/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NodeType from './NodeType';
import PermissionManagementModel from './PermissionManagementModel';
import RequestMetadata from './RequestMetadata';
import RequestStatus from './RequestStatus';
import SPGroupManagementModel from './SPGroupManagementModel';
import ServiceType from './ServiceType';

/**
 * The ManagePermissionRequest model module.
 * @module model/ManagePermissionRequest
 * @version 1.0
 */
class ManagePermissionRequest {
    /**
     * Constructs a new <code>ManagePermissionRequest</code>.
     * @alias module:model/ManagePermissionRequest
     */
    constructor() { 
        
        ManagePermissionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ManagePermissionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManagePermissionRequest} obj Optional instance to populate.
     * @return {module:model/ManagePermissionRequest} The populated <code>ManagePermissionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagePermissionRequest();

            if (data.hasOwnProperty('objectUrl')) {
                obj['objectUrl'] = ApiClient.convertToType(data['objectUrl'], 'String');
            }
            if (data.hasOwnProperty('objectType')) {
                obj['objectType'] = NodeType.constructFromObject(data['objectType']);
            }
            if (data.hasOwnProperty('objectTitle')) {
                obj['objectTitle'] = ApiClient.convertToType(data['objectTitle'], 'String');
            }
            if (data.hasOwnProperty('siteUrl')) {
                obj['siteUrl'] = ApiClient.convertToType(data['siteUrl'], 'String');
            }
            if (data.hasOwnProperty('webUrl')) {
                obj['webUrl'] = ApiClient.convertToType(data['webUrl'], 'String');
            }
            if (data.hasOwnProperty('spGroupManagement')) {
                obj['spGroupManagement'] = ApiClient.convertToType(data['spGroupManagement'], [SPGroupManagementModel]);
            }
            if (data.hasOwnProperty('permissionManagement')) {
                obj['permissionManagement'] = PermissionManagementModel.constructFromObject(data['permissionManagement']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('notesToApprovers')) {
                obj['notesToApprovers'] = ApiClient.convertToType(data['notesToApprovers'], 'String');
            }
            if (data.hasOwnProperty('questionnaireId')) {
                obj['questionnaireId'] = ApiClient.convertToType(data['questionnaireId'], 'String');
            }
            if (data.hasOwnProperty('metadatas')) {
                obj['metadatas'] = ApiClient.convertToType(data['metadatas'], [RequestMetadata]);
            }
            if (data.hasOwnProperty('ticketNumber')) {
                obj['ticketNumber'] = ApiClient.convertToType(data['ticketNumber'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ServiceType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('typeDescription')) {
                obj['typeDescription'] = ApiClient.convertToType(data['typeDescription'], 'String');
            }
            if (data.hasOwnProperty('requester')) {
                obj['requester'] = ApiClient.convertToType(data['requester'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = RequestStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('progressStatus')) {
                obj['progressStatus'] = ApiClient.convertToType(data['progressStatus'], 'Number');
            }
            if (data.hasOwnProperty('progressStatusDescription')) {
                obj['progressStatusDescription'] = ApiClient.convertToType(data['progressStatusDescription'], 'String');
            }
            if (data.hasOwnProperty('submittedTime')) {
                obj['submittedTime'] = ApiClient.convertToType(data['submittedTime'], 'Date');
            }
            if (data.hasOwnProperty('lastUpdated')) {
                obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
            }
            if (data.hasOwnProperty('createdTime')) {
                obj['createdTime'] = ApiClient.convertToType(data['createdTime'], 'Date');
            }
            if (data.hasOwnProperty('assignTo')) {
                obj['assignTo'] = ApiClient.convertToType(data['assignTo'], 'String');
            }
            if (data.hasOwnProperty('fullPath')) {
                obj['fullPath'] = ApiClient.convertToType(data['fullPath'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} objectUrl
 */
ManagePermissionRequest.prototype['objectUrl'] = undefined;

/**
 * @member {module:model/NodeType} objectType
 */
ManagePermissionRequest.prototype['objectType'] = undefined;

/**
 * @member {String} objectTitle
 */
ManagePermissionRequest.prototype['objectTitle'] = undefined;

/**
 * @member {String} siteUrl
 */
ManagePermissionRequest.prototype['siteUrl'] = undefined;

/**
 * @member {String} webUrl
 */
ManagePermissionRequest.prototype['webUrl'] = undefined;

/**
 * @member {Array.<module:model/SPGroupManagementModel>} spGroupManagement
 */
ManagePermissionRequest.prototype['spGroupManagement'] = undefined;

/**
 * @member {module:model/PermissionManagementModel} permissionManagement
 */
ManagePermissionRequest.prototype['permissionManagement'] = undefined;

/**
 * @member {String} id
 */
ManagePermissionRequest.prototype['id'] = undefined;

/**
 * @member {String} serviceId
 */
ManagePermissionRequest.prototype['serviceId'] = undefined;

/**
 * @member {String} department
 */
ManagePermissionRequest.prototype['department'] = undefined;

/**
 * @member {String} summary
 */
ManagePermissionRequest.prototype['summary'] = undefined;

/**
 * @member {String} notesToApprovers
 */
ManagePermissionRequest.prototype['notesToApprovers'] = undefined;

/**
 * @member {String} questionnaireId
 */
ManagePermissionRequest.prototype['questionnaireId'] = undefined;

/**
 * @member {Array.<module:model/RequestMetadata>} metadatas
 */
ManagePermissionRequest.prototype['metadatas'] = undefined;

/**
 * @member {Number} ticketNumber
 */
ManagePermissionRequest.prototype['ticketNumber'] = undefined;

/**
 * @member {module:model/ServiceType} type
 */
ManagePermissionRequest.prototype['type'] = undefined;

/**
 * @member {String} typeDescription
 */
ManagePermissionRequest.prototype['typeDescription'] = undefined;

/**
 * @member {String} requester
 */
ManagePermissionRequest.prototype['requester'] = undefined;

/**
 * @member {module:model/RequestStatus} status
 */
ManagePermissionRequest.prototype['status'] = undefined;

/**
 * @member {Number} progressStatus
 */
ManagePermissionRequest.prototype['progressStatus'] = undefined;

/**
 * @member {String} progressStatusDescription
 */
ManagePermissionRequest.prototype['progressStatusDescription'] = undefined;

/**
 * @member {Date} submittedTime
 */
ManagePermissionRequest.prototype['submittedTime'] = undefined;

/**
 * @member {Date} lastUpdated
 */
ManagePermissionRequest.prototype['lastUpdated'] = undefined;

/**
 * @member {Date} createdTime
 */
ManagePermissionRequest.prototype['createdTime'] = undefined;

/**
 * @member {String} assignTo
 */
ManagePermissionRequest.prototype['assignTo'] = undefined;

/**
 * @member {String} fullPath
 */
ManagePermissionRequest.prototype['fullPath'] = undefined;






export default ManagePermissionRequest;

