/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiUser from './ApiUser';
import ExternalUserType from './ExternalUserType';
import GrantPermissionModel from './GrantPermissionModel';
import ManagePermissionAction from './ManagePermissionAction';
import SPPrincipalType from './SPPrincipalType';
import SharingEnabledUser from './SharingEnabledUser';

/**
 * The ObjectPermissionManagementModel model module.
 * @module model/ObjectPermissionManagementModel
 * @version 1.0
 */
class ObjectPermissionManagementModel {
    /**
     * Constructs a new <code>ObjectPermissionManagementModel</code>.
     * @alias module:model/ObjectPermissionManagementModel
     */
    constructor() { 
        
        ObjectPermissionManagementModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ObjectPermissionManagementModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectPermissionManagementModel} obj Optional instance to populate.
     * @return {module:model/ObjectPermissionManagementModel} The populated <code>ObjectPermissionManagementModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectPermissionManagementModel();

            if (data.hasOwnProperty('objectType')) {
                obj['objectType'] = SPPrincipalType.constructFromObject(data['objectType']);
            }
            if (data.hasOwnProperty('objectInfo')) {
                obj['objectInfo'] = ApiUser.constructFromObject(data['objectInfo']);
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ManagePermissionAction.constructFromObject(data['action']);
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], ['String']);
            }
            if (data.hasOwnProperty('originalPermissions')) {
                obj['originalPermissions'] = ApiClient.convertToType(data['originalPermissions'], ['String']);
            }
            if (data.hasOwnProperty('externalUserType')) {
                obj['externalUserType'] = ExternalUserType.constructFromObject(data['externalUserType']);
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [SharingEnabledUser]);
            }
            if (data.hasOwnProperty('grantPermissionSetting')) {
                obj['grantPermissionSetting'] = GrantPermissionModel.constructFromObject(data['grantPermissionSetting']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SPPrincipalType} objectType
 */
ObjectPermissionManagementModel.prototype['objectType'] = undefined;

/**
 * @member {module:model/ApiUser} objectInfo
 */
ObjectPermissionManagementModel.prototype['objectInfo'] = undefined;

/**
 * @member {module:model/ManagePermissionAction} action
 */
ObjectPermissionManagementModel.prototype['action'] = undefined;

/**
 * @member {Array.<String>} permissions
 */
ObjectPermissionManagementModel.prototype['permissions'] = undefined;

/**
 * @member {Array.<String>} originalPermissions
 */
ObjectPermissionManagementModel.prototype['originalPermissions'] = undefined;

/**
 * @member {module:model/ExternalUserType} externalUserType
 */
ObjectPermissionManagementModel.prototype['externalUserType'] = undefined;

/**
 * @member {Array.<module:model/SharingEnabledUser>} members
 */
ObjectPermissionManagementModel.prototype['members'] = undefined;

/**
 * @member {module:model/GrantPermissionModel} grantPermissionSetting
 */
ObjectPermissionManagementModel.prototype['grantPermissionSetting'] = undefined;






export default ObjectPermissionManagementModel;

