/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PolicyRecertificationSetting model module.
 * @module model/PolicyRecertificationSetting
 * @version 1.0
 */
class PolicyRecertificationSetting {
    /**
     * Constructs a new <code>PolicyRecertificationSetting</code>.
     * @alias module:model/PolicyRecertificationSetting
     */
    constructor() { 
        
        PolicyRecertificationSetting.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PolicyRecertificationSetting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PolicyRecertificationSetting} obj Optional instance to populate.
     * @return {module:model/PolicyRecertificationSetting} The populated <code>PolicyRecertificationSetting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PolicyRecertificationSetting();

            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('profileId')) {
                obj['profileId'] = ApiClient.convertToType(data['profileId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isEnabled
 */
PolicyRecertificationSetting.prototype['isEnabled'] = undefined;

/**
 * @member {String} profileId
 */
PolicyRecertificationSetting.prototype['profileId'] = undefined;






export default PolicyRecertificationSetting;

