/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class QuestionnaireNodeType.
* @enum {}
* @readonly
*/
export default class QuestionnaireNodeType {
    
        /**
         * value: "StartState"
         * @const
         */
        "StartState" = "StartState";

    
        /**
         * value: "Question"
         * @const
         */
        "Question" = "Question";

    
        /**
         * value: "Service"
         * @const
         */
        "Service" = "Service";

    
        /**
         * value: "EndState"
         * @const
         */
        "EndState" = "EndState";

    
        /**
         * value: "Joint"
         * @const
         */
        "Joint" = "Joint";

    

    /**
    * Returns a <code>QuestionnaireNodeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/QuestionnaireNodeType} The enum <code>QuestionnaireNodeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

