/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UrlRandomStringSettings model module.
 * @module model/UrlRandomStringSettings
 * @version 1.0
 */
class UrlRandomStringSettings {
    /**
     * Constructs a new <code>UrlRandomStringSettings</code>.
     * @alias module:model/UrlRandomStringSettings
     */
    constructor() { 
        
        UrlRandomStringSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UrlRandomStringSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UrlRandomStringSettings} obj Optional instance to populate.
     * @return {module:model/UrlRandomStringSettings} The populated <code>UrlRandomStringSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UrlRandomStringSettings();

            if (data.hasOwnProperty('prefix')) {
                obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
            }
            if (data.hasOwnProperty('maxLength')) {
                obj['maxLength'] = ApiClient.convertToType(data['maxLength'], 'Number');
            }
            if (data.hasOwnProperty('minLength')) {
                obj['minLength'] = ApiClient.convertToType(data['minLength'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} prefix
 */
UrlRandomStringSettings.prototype['prefix'] = undefined;

/**
 * @member {Number} maxLength
 */
UrlRandomStringSettings.prototype['maxLength'] = undefined;

/**
 * @member {Number} minLength
 */
UrlRandomStringSettings.prototype['minLength'] = undefined;






export default UrlRandomStringSettings;

