/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnnoymouslinkPermissions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AnnoymouslinkPermissions'));
  } else {
    // Browser globals (root is window)
    if (!root.CgClient) {
      root.CgClient = {};
    }
    root.CgClient.AnonymousLinkSettings = factory(root.CgClient.ApiClient, root.CgClient.AnnoymouslinkPermissions);
  }
}(this, function(ApiClient, AnnoymouslinkPermissions) {
  'use strict';



  /**
   * The AnonymousLinkSettings model module.
   * @module model/AnonymousLinkSettings
   * @version 1.0
   */

  /**
   * Constructs a new <code>AnonymousLinkSettings</code>.
   * @alias module:model/AnonymousLinkSettings
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>AnonymousLinkSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnonymousLinkSettings} obj Optional instance to populate.
   * @return {module:model/AnonymousLinkSettings} The populated <code>AnonymousLinkSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('permisssion')) {
        obj['permisssion'] = AnnoymouslinkPermissions.constructFromObject(data['permisssion']);
      }
      if (data.hasOwnProperty('expirationDate')) {
        obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AnnoymouslinkPermissions} permisssion
   */
  exports.prototype['permisssion'] = undefined;
  /**
   * @member {Date} expirationDate
   */
  exports.prototype['expirationDate'] = undefined;



  return exports;
}));


