/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CgClient) {
      root.CgClient = {};
    }
    root.CgClient.BooleanMetadataSettings = factory(root.CgClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The BooleanMetadataSettings model module.
   * @module model/BooleanMetadataSettings
   * @version 1.0
   */

  /**
   * Constructs a new <code>BooleanMetadataSettings</code>.
   * @alias module:model/BooleanMetadataSettings
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>BooleanMetadataSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BooleanMetadataSettings} obj Optional instance to populate.
   * @return {module:model/BooleanMetadataSettings} The populated <code>BooleanMetadataSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('enableTerms')) {
        obj['enableTerms'] = ApiClient.convertToType(data['enableTerms'], 'Boolean');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Boolean');
      }
      if (data.hasOwnProperty('termsAndConditions')) {
        obj['termsAndConditions'] = ApiClient.convertToType(data['termsAndConditions'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} enableTerms
   */
  exports.prototype['enableTerms'] = undefined;
  /**
   * @member {Boolean} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {String} termsAndConditions
   */
  exports.prototype['termsAndConditions'] = undefined;



  return exports;
}));


