/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiUser', 'model/PermissionActionType', 'model/PrincipalType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApiUser'), require('./PermissionActionType'), require('./PrincipalType'));
  } else {
    // Browser globals (root is window)
    if (!root.CgClient) {
      root.CgClient = {};
    }
    root.CgClient.PermissionChangedActionItem = factory(root.CgClient.ApiClient, root.CgClient.ApiUser, root.CgClient.PermissionActionType, root.CgClient.PrincipalType);
  }
}(this, function(ApiClient, ApiUser, PermissionActionType, PrincipalType) {
  'use strict';



  /**
   * The PermissionChangedActionItem model module.
   * @module model/PermissionChangedActionItem
   * @version 1.0
   */

  /**
   * Constructs a new <code>PermissionChangedActionItem</code>.
   * @alias module:model/PermissionChangedActionItem
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>PermissionChangedActionItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PermissionChangedActionItem} obj Optional instance to populate.
   * @return {module:model/PermissionChangedActionItem} The populated <code>PermissionChangedActionItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('groupChanges')) {
        obj['groupChanges'] = ApiClient.convertToType(data['groupChanges'], 'String');
      }
      if (data.hasOwnProperty('permissionChanges')) {
        obj['permissionChanges'] = ApiClient.convertToType(data['permissionChanges'], 'String');
      }
      if (data.hasOwnProperty('accountType')) {
        obj['accountType'] = PrincipalType.constructFromObject(data['accountType']);
      }
      if (data.hasOwnProperty('accountTypeDescription')) {
        obj['accountTypeDescription'] = ApiClient.convertToType(data['accountTypeDescription'], 'String');
      }
      if (data.hasOwnProperty('actionType')) {
        obj['actionType'] = PermissionActionType.constructFromObject(data['actionType']);
      }
      if (data.hasOwnProperty('actionTypeDescription')) {
        obj['actionTypeDescription'] = ApiClient.convertToType(data['actionTypeDescription'], 'String');
      }
      if (data.hasOwnProperty('changedBy')) {
        obj['changedBy'] = ApiUser.constructFromObject(data['changedBy']);
      }
      if (data.hasOwnProperty('objectTitle')) {
        obj['objectTitle'] = ApiClient.convertToType(data['objectTitle'], 'String');
      }
      if (data.hasOwnProperty('objectUrl')) {
        obj['objectUrl'] = ApiClient.convertToType(data['objectUrl'], 'String');
      }
      if (data.hasOwnProperty('objectType')) {
        obj['objectType'] = ApiClient.convertToType(data['objectType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} groupChanges
   */
  exports.prototype['groupChanges'] = undefined;
  /**
   * @member {String} permissionChanges
   */
  exports.prototype['permissionChanges'] = undefined;
  /**
   * @member {module:model/PrincipalType} accountType
   */
  exports.prototype['accountType'] = undefined;
  /**
   * @member {String} accountTypeDescription
   */
  exports.prototype['accountTypeDescription'] = undefined;
  /**
   * @member {module:model/PermissionActionType} actionType
   */
  exports.prototype['actionType'] = undefined;
  /**
   * @member {String} actionTypeDescription
   */
  exports.prototype['actionTypeDescription'] = undefined;
  /**
   * @member {module:model/ApiUser} changedBy
   */
  exports.prototype['changedBy'] = undefined;
  /**
   * @member {String} objectTitle
   */
  exports.prototype['objectTitle'] = undefined;
  /**
   * @member {String} objectUrl
   */
  exports.prototype['objectUrl'] = undefined;
  /**
   * @member {String} objectType
   */
  exports.prototype['objectType'] = undefined;



  return exports;
}));


