/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing ApplyPolicyInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplyPolicyInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplyPolicyInfo
        //private ApplyPolicyInfo instance;

        public ApplyPolicyInfoTests()
        {
            // TODO uncomment below to create an instance of ApplyPolicyInfo
            //instance = new ApplyPolicyInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplyPolicyInfo
        /// </summary>
        [Fact]
        public void ApplyPolicyInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplyPolicyInfo
            //Assert.IsInstanceOfType<ApplyPolicyInfo> (instance, "variable 'instance' is a ApplyPolicyInfo");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LastChangeTime'
        /// </summary>
        [Fact]
        public void LastChangeTimeTest()
        {
            // TODO unit test for the property 'LastChangeTime'
        }
        /// <summary>
        /// Test the property 'LifeCycleStartTime'
        /// </summary>
        [Fact]
        public void LifeCycleStartTimeTest()
        {
            // TODO unit test for the property 'LifeCycleStartTime'
        }

    }

}
