/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing AzureAdMetadataSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AzureAdMetadataSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AzureAdMetadataSettings
        //private AzureAdMetadataSettings instance;

        public AzureAdMetadataSettingsTests()
        {
            // TODO uncomment below to create an instance of AzureAdMetadataSettings
            //instance = new AzureAdMetadataSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AzureAdMetadataSettings
        /// </summary>
        [Fact]
        public void AzureAdMetadataSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AzureAdMetadataSettings
            //Assert.IsInstanceOfType<AzureAdMetadataSettings> (instance, "variable 'instance' is a AzureAdMetadataSettings");
        }


        /// <summary>
        /// Test the property 'Office365Tenant'
        /// </summary>
        [Fact]
        public void Office365TenantTest()
        {
            // TODO unit test for the property 'Office365Tenant'
        }
        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Fact]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
