/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing ChangeGroupSettingCheckResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangeGroupSettingCheckResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangeGroupSettingCheckResult
        //private ChangeGroupSettingCheckResult instance;

        public ChangeGroupSettingCheckResultTests()
        {
            // TODO uncomment below to create an instance of ChangeGroupSettingCheckResult
            //instance = new ChangeGroupSettingCheckResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangeGroupSettingCheckResult
        /// </summary>
        [Fact]
        public void ChangeGroupSettingCheckResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangeGroupSettingCheckResult
            //Assert.IsInstanceOfType<ChangeGroupSettingCheckResult> (instance, "variable 'instance' is a ChangeGroupSettingCheckResult");
        }


        /// <summary>
        /// Test the property 'PrimaryContact'
        /// </summary>
        [Fact]
        public void PrimaryContactTest()
        {
            // TODO unit test for the property 'PrimaryContact'
        }
        /// <summary>
        /// Test the property 'SecondaryContact'
        /// </summary>
        [Fact]
        public void SecondaryContactTest()
        {
            // TODO unit test for the property 'SecondaryContact'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
        /// <summary>
        /// Test the property 'GroupEmail'
        /// </summary>
        [Fact]
        public void GroupEmailTest()
        {
            // TODO unit test for the property 'GroupEmail'
        }
        /// <summary>
        /// Test the property 'GroupDescription'
        /// </summary>
        [Fact]
        public void GroupDescriptionTest()
        {
            // TODO unit test for the property 'GroupDescription'
        }
        /// <summary>
        /// Test the property 'IsEnableSubscribeMembers'
        /// </summary>
        [Fact]
        public void IsEnableSubscribeMembersTest()
        {
            // TODO unit test for the property 'IsEnableSubscribeMembers'
        }
        /// <summary>
        /// Test the property 'IsEnableOutsideSender'
        /// </summary>
        [Fact]
        public void IsEnableOutsideSenderTest()
        {
            // TODO unit test for the property 'IsEnableOutsideSender'
        }
        /// <summary>
        /// Test the property 'Classification'
        /// </summary>
        [Fact]
        public void ClassificationTest()
        {
            // TODO unit test for the property 'Classification'
        }
        /// <summary>
        /// Test the property 'IsTeamsEnabled'
        /// </summary>
        [Fact]
        public void IsTeamsEnabledTest()
        {
            // TODO unit test for the property 'IsTeamsEnabled'
        }
        /// <summary>
        /// Test the property 'EnableManageGroupSharing'
        /// </summary>
        [Fact]
        public void EnableManageGroupSharingTest()
        {
            // TODO unit test for the property 'EnableManageGroupSharing'
        }
        /// <summary>
        /// Test the property 'EnableInviteAuthorizedGuestUser'
        /// </summary>
        [Fact]
        public void EnableInviteAuthorizedGuestUserTest()
        {
            // TODO unit test for the property 'EnableInviteAuthorizedGuestUser'
        }
        /// <summary>
        /// Test the property 'EnableInviteGuestUser'
        /// </summary>
        [Fact]
        public void EnableInviteGuestUserTest()
        {
            // TODO unit test for the property 'EnableInviteGuestUser'
        }
        /// <summary>
        /// Test the property 'EnableDynamicMembership'
        /// </summary>
        [Fact]
        public void EnableDynamicMembershipTest()
        {
            // TODO unit test for the property 'EnableDynamicMembership'
        }
        /// <summary>
        /// Test the property 'IsHubSite'
        /// </summary>
        [Fact]
        public void IsHubSiteTest()
        {
            // TODO unit test for the property 'IsHubSite'
        }
        /// <summary>
        /// Test the property 'AssociatedHubSiteId'
        /// </summary>
        [Fact]
        public void AssociatedHubSiteIdTest()
        {
            // TODO unit test for the property 'AssociatedHubSiteId'
        }
        /// <summary>
        /// Test the property 'DynamicMembershipRules'
        /// </summary>
        [Fact]
        public void DynamicMembershipRulesTest()
        {
            // TODO unit test for the property 'DynamicMembershipRules'
        }
        /// <summary>
        /// Test the property 'Metadatas'
        /// </summary>
        [Fact]
        public void MetadatasTest()
        {
            // TODO unit test for the property 'Metadatas'
        }
        /// <summary>
        /// Test the property 'IsValid'
        /// </summary>
        [Fact]
        public void IsValidTest()
        {
            // TODO unit test for the property 'IsValid'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
