/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing ClonePermissionAdditionalOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClonePermissionAdditionalOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClonePermissionAdditionalOption
        //private ClonePermissionAdditionalOption instance;

        public ClonePermissionAdditionalOptionTests()
        {
            // TODO uncomment below to create an instance of ClonePermissionAdditionalOption
            //instance = new ClonePermissionAdditionalOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClonePermissionAdditionalOption
        /// </summary>
        [Fact]
        public void ClonePermissionAdditionalOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClonePermissionAdditionalOption
            //Assert.IsInstanceOfType<ClonePermissionAdditionalOption> (instance, "variable 'instance' is a ClonePermissionAdditionalOption");
        }



    }

}
