/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing ContentMoveSPObjectMapping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentMoveSPObjectMappingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentMoveSPObjectMapping
        //private ContentMoveSPObjectMapping instance;

        public ContentMoveSPObjectMappingTests()
        {
            // TODO uncomment below to create an instance of ContentMoveSPObjectMapping
            //instance = new ContentMoveSPObjectMapping();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentMoveSPObjectMapping
        /// </summary>
        [Fact]
        public void ContentMoveSPObjectMappingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContentMoveSPObjectMapping
            //Assert.IsInstanceOfType<ContentMoveSPObjectMapping> (instance, "variable 'instance' is a ContentMoveSPObjectMapping");
        }


        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Fact]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

    }

}
