/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing CreateWebService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateWebServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateWebService
        //private CreateWebService instance;

        public CreateWebServiceTests()
        {
            // TODO uncomment below to create an instance of CreateWebService
            //instance = new CreateWebService();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateWebService
        /// </summary>
        [Fact]
        public void CreateWebServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateWebService
            //Assert.IsInstanceOfType<CreateWebService> (instance, "variable 'instance' is a CreateWebService");
        }


        /// <summary>
        /// Test the property 'ScopeSettings'
        /// </summary>
        [Fact]
        public void ScopeSettingsTest()
        {
            // TODO unit test for the property 'ScopeSettings'
        }
        /// <summary>
        /// Test the property 'WebLanguages'
        /// </summary>
        [Fact]
        public void WebLanguagesTest()
        {
            // TODO unit test for the property 'WebLanguages'
        }
        /// <summary>
        /// Test the property 'LanguageIdsAndTemplates'
        /// </summary>
        [Fact]
        public void LanguageIdsAndTemplatesTest()
        {
            // TODO unit test for the property 'LanguageIdsAndTemplates'
        }
        /// <summary>
        /// Test the property 'TemplateIdsAndPermissions'
        /// </summary>
        [Fact]
        public void TemplateIdsAndPermissionsTest()
        {
            // TODO unit test for the property 'TemplateIdsAndPermissions'
        }
        /// <summary>
        /// Test the property 'PermissionSettings'
        /// </summary>
        [Fact]
        public void PermissionSettingsTest()
        {
            // TODO unit test for the property 'PermissionSettings'
        }
        /// <summary>
        /// Test the property 'UseUniquePermissions'
        /// </summary>
        [Fact]
        public void UseUniquePermissionsTest()
        {
            // TODO unit test for the property 'UseUniquePermissions'
        }
        /// <summary>
        /// Test the property 'DeploymentManagerPlanSettings'
        /// </summary>
        [Fact]
        public void DeploymentManagerPlanSettingsTest()
        {
            // TODO unit test for the property 'DeploymentManagerPlanSettings'
        }
        /// <summary>
        /// Test the property 'YammerGroupSettings'
        /// </summary>
        [Fact]
        public void YammerGroupSettingsTest()
        {
            // TODO unit test for the property 'YammerGroupSettings'
        }
        /// <summary>
        /// Test the property 'TemplateStoreUrl'
        /// </summary>
        [Fact]
        public void TemplateStoreUrlTest()
        {
            // TODO unit test for the property 'TemplateStoreUrl'
        }
        /// <summary>
        /// Test the property 'AppSettings'
        /// </summary>
        [Fact]
        public void AppSettingsTest()
        {
            // TODO unit test for the property 'AppSettings'
        }
        /// <summary>
        /// Test the property 'NotifyPrimaryContactSettings'
        /// </summary>
        [Fact]
        public void NotifyPrimaryContactSettingsTest()
        {
            // TODO unit test for the property 'NotifyPrimaryContactSettings'
        }
        /// <summary>
        /// Test the property 'NotifySecondaryContactSettings'
        /// </summary>
        [Fact]
        public void NotifySecondaryContactSettingsTest()
        {
            // TODO unit test for the property 'NotifySecondaryContactSettings'
        }
        /// <summary>
        /// Test the property 'DefaultPrimaryContact'
        /// </summary>
        [Fact]
        public void DefaultPrimaryContactTest()
        {
            // TODO unit test for the property 'DefaultPrimaryContact'
        }
        /// <summary>
        /// Test the property 'DefaultSecondaryContact'
        /// </summary>
        [Fact]
        public void DefaultSecondaryContactTest()
        {
            // TODO unit test for the property 'DefaultSecondaryContact'
        }
        /// <summary>
        /// Test the property 'IsOnQuickLaunch'
        /// </summary>
        [Fact]
        public void IsOnQuickLaunchTest()
        {
            // TODO unit test for the property 'IsOnQuickLaunch'
        }
        /// <summary>
        /// Test the property 'IsOnTopLinkBar'
        /// </summary>
        [Fact]
        public void IsOnTopLinkBarTest()
        {
            // TODO unit test for the property 'IsOnTopLinkBar'
        }
        /// <summary>
        /// Test the property 'IsNavigationInheritance'
        /// </summary>
        [Fact]
        public void IsNavigationInheritanceTest()
        {
            // TODO unit test for the property 'IsNavigationInheritance'
        }
        /// <summary>
        /// Test the property 'DefaultWebLanguage'
        /// </summary>
        [Fact]
        public void DefaultWebLanguageTest()
        {
            // TODO unit test for the property 'DefaultWebLanguage'
        }
        /// <summary>
        /// Test the property 'ScopeAssignBy'
        /// </summary>
        [Fact]
        public void ScopeAssignByTest()
        {
            // TODO unit test for the property 'ScopeAssignBy'
        }
        /// <summary>
        /// Test the property 'WebLanguageAssignBy'
        /// </summary>
        [Fact]
        public void WebLanguageAssignByTest()
        {
            // TODO unit test for the property 'WebLanguageAssignBy'
        }
        /// <summary>
        /// Test the property 'TemplateAssignBy'
        /// </summary>
        [Fact]
        public void TemplateAssignByTest()
        {
            // TODO unit test for the property 'TemplateAssignBy'
        }
        /// <summary>
        /// Test the property 'NavigationInheritanceAssignBy'
        /// </summary>
        [Fact]
        public void NavigationInheritanceAssignByTest()
        {
            // TODO unit test for the property 'NavigationInheritanceAssignBy'
        }
        /// <summary>
        /// Test the property 'NavigationAssignBy'
        /// </summary>
        [Fact]
        public void NavigationAssignByTest()
        {
            // TODO unit test for the property 'NavigationAssignBy'
        }
        /// <summary>
        /// Test the property 'PrimaryContactAssignBy'
        /// </summary>
        [Fact]
        public void PrimaryContactAssignByTest()
        {
            // TODO unit test for the property 'PrimaryContactAssignBy'
        }
        /// <summary>
        /// Test the property 'SecondaryContactAssignBy'
        /// </summary>
        [Fact]
        public void SecondaryContactAssignByTest()
        {
            // TODO unit test for the property 'SecondaryContactAssignBy'
        }
        /// <summary>
        /// Test the property 'PermissionAssignBy'
        /// </summary>
        [Fact]
        public void PermissionAssignByTest()
        {
            // TODO unit test for the property 'PermissionAssignBy'
        }
        /// <summary>
        /// Test the property 'DepartmentAssignBy'
        /// </summary>
        [Fact]
        public void DepartmentAssignByTest()
        {
            // TODO unit test for the property 'DepartmentAssignBy'
        }
        /// <summary>
        /// Test the property 'Metadatas'
        /// </summary>
        [Fact]
        public void MetadatasTest()
        {
            // TODO unit test for the property 'Metadatas'
        }
        /// <summary>
        /// Test the property 'HideRequestSummary'
        /// </summary>
        [Fact]
        public void HideRequestSummaryTest()
        {
            // TODO unit test for the property 'HideRequestSummary'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'LoadDepartmentFromUps'
        /// </summary>
        [Fact]
        public void LoadDepartmentFromUpsTest()
        {
            // TODO unit test for the property 'LoadDepartmentFromUps'
        }
        /// <summary>
        /// Test the property 'Departments'
        /// </summary>
        [Fact]
        public void DepartmentsTest()
        {
            // TODO unit test for the property 'Departments'
        }
        /// <summary>
        /// Test the property 'ServiceContact'
        /// </summary>
        [Fact]
        public void ServiceContactTest()
        {
            // TODO unit test for the property 'ServiceContact'
        }
        /// <summary>
        /// Test the property 'ServiceAdminContact'
        /// </summary>
        [Fact]
        public void ServiceAdminContactTest()
        {
            // TODO unit test for the property 'ServiceAdminContact'
        }
        /// <summary>
        /// Test the property 'ApproversContainManagerRole'
        /// </summary>
        [Fact]
        public void ApproversContainManagerRoleTest()
        {
            // TODO unit test for the property 'ApproversContainManagerRole'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ShowServiceInCatalog'
        /// </summary>
        [Fact]
        public void ShowServiceInCatalogTest()
        {
            // TODO unit test for the property 'ShowServiceInCatalog'
        }
        /// <summary>
        /// Test the property 'CustomActivity'
        /// </summary>
        [Fact]
        public void CustomActivityTest()
        {
            // TODO unit test for the property 'CustomActivity'
        }
        /// <summary>
        /// Test the property 'ApprovalProcessId'
        /// </summary>
        [Fact]
        public void ApprovalProcessIdTest()
        {
            // TODO unit test for the property 'ApprovalProcessId'
        }
        /// <summary>
        /// Test the property 'LanguageId'
        /// </summary>
        [Fact]
        public void LanguageIdTest()
        {
            // TODO unit test for the property 'LanguageId'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }

    }

}
