/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing CustomMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomMetadata
        //private CustomMetadata instance;

        public CustomMetadataTests()
        {
            // TODO uncomment below to create an instance of CustomMetadata
            //instance = new CustomMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomMetadata
        /// </summary>
        [Fact]
        public void CustomMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomMetadata
            //Assert.IsInstanceOfType<CustomMetadata> (instance, "variable 'instance' is a CustomMetadata");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'DisplayType'
        /// </summary>
        [Fact]
        public void DisplayTypeTest()
        {
            // TODO unit test for the property 'DisplayType'
        }
        /// <summary>
        /// Test the property 'AssignBy'
        /// </summary>
        [Fact]
        public void AssignByTest()
        {
            // TODO unit test for the property 'AssignBy'
        }
        /// <summary>
        /// Test the property 'EnableTextValidation'
        /// </summary>
        [Fact]
        public void EnableTextValidationTest()
        {
            // TODO unit test for the property 'EnableTextValidation'
        }
        /// <summary>
        /// Test the property 'TextValidationRule'
        /// </summary>
        [Fact]
        public void TextValidationRuleTest()
        {
            // TODO unit test for the property 'TextValidationRule'
        }
        /// <summary>
        /// Test the property 'BooleanMetadataSettings'
        /// </summary>
        [Fact]
        public void BooleanMetadataSettingsTest()
        {
            // TODO unit test for the property 'BooleanMetadataSettings'
        }
        /// <summary>
        /// Test the property 'TermsMetadataSettings'
        /// </summary>
        [Fact]
        public void TermsMetadataSettingsTest()
        {
            // TODO unit test for the property 'TermsMetadataSettings'
        }
        /// <summary>
        /// Test the property 'UserMetadataSettings'
        /// </summary>
        [Fact]
        public void UserMetadataSettingsTest()
        {
            // TODO unit test for the property 'UserMetadataSettings'
        }
        /// <summary>
        /// Test the property 'UserProfileMetadataSettings'
        /// </summary>
        [Fact]
        public void UserProfileMetadataSettingsTest()
        {
            // TODO unit test for the property 'UserProfileMetadataSettings'
        }
        /// <summary>
        /// Test the property 'AzureAdMetadataSettings'
        /// </summary>
        [Fact]
        public void AzureAdMetadataSettingsTest()
        {
            // TODO unit test for the property 'AzureAdMetadataSettings'
        }
        /// <summary>
        /// Test the property 'ChoiceMetadataSettings'
        /// </summary>
        [Fact]
        public void ChoiceMetadataSettingsTest()
        {
            // TODO unit test for the property 'ChoiceMetadataSettings'
        }
        /// <summary>
        /// Test the property 'LinkMetadataSettings'
        /// </summary>
        [Fact]
        public void LinkMetadataSettingsTest()
        {
            // TODO unit test for the property 'LinkMetadataSettings'
        }
        /// <summary>
        /// Test the property 'SingleLineOrMultipleLineMetadataSettings'
        /// </summary>
        [Fact]
        public void SingleLineOrMultipleLineMetadataSettingsTest()
        {
            // TODO unit test for the property 'SingleLineOrMultipleLineMetadataSettings'
        }

    }

}
