/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing GrantPermissionService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GrantPermissionServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GrantPermissionService
        //private GrantPermissionService instance;

        public GrantPermissionServiceTests()
        {
            // TODO uncomment below to create an instance of GrantPermissionService
            //instance = new GrantPermissionService();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GrantPermissionService
        /// </summary>
        [Fact]
        public void GrantPermissionServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GrantPermissionService
            //Assert.IsInstanceOfType<GrantPermissionService> (instance, "variable 'instance' is a GrantPermissionService");
        }


        /// <summary>
        /// Test the property 'AllowBreakPermissionInheritance'
        /// </summary>
        [Fact]
        public void AllowBreakPermissionInheritanceTest()
        {
            // TODO unit test for the property 'AllowBreakPermissionInheritance'
        }
        /// <summary>
        /// Test the property 'UserLevelControlSettings'
        /// </summary>
        [Fact]
        public void UserLevelControlSettingsTest()
        {
            // TODO unit test for the property 'UserLevelControlSettings'
        }
        /// <summary>
        /// Test the property 'PermissionDurationSettings'
        /// </summary>
        [Fact]
        public void PermissionDurationSettingsTest()
        {
            // TODO unit test for the property 'PermissionDurationSettings'
        }
        /// <summary>
        /// Test the property 'PermissionSettings'
        /// </summary>
        [Fact]
        public void PermissionSettingsTest()
        {
            // TODO unit test for the property 'PermissionSettings'
        }
        /// <summary>
        /// Test the property 'DefaultWelcomeEmailSettings'
        /// </summary>
        [Fact]
        public void DefaultWelcomeEmailSettingsTest()
        {
            // TODO unit test for the property 'DefaultWelcomeEmailSettings'
        }
        /// <summary>
        /// Test the property 'WelcomeEmailAssignBy'
        /// </summary>
        [Fact]
        public void WelcomeEmailAssignByTest()
        {
            // TODO unit test for the property 'WelcomeEmailAssignBy'
        }
        /// <summary>
        /// Test the property 'DepartmentAssignBy'
        /// </summary>
        [Fact]
        public void DepartmentAssignByTest()
        {
            // TODO unit test for the property 'DepartmentAssignBy'
        }
        /// <summary>
        /// Test the property 'Metadatas'
        /// </summary>
        [Fact]
        public void MetadatasTest()
        {
            // TODO unit test for the property 'Metadatas'
        }
        /// <summary>
        /// Test the property 'HideRequestSummary'
        /// </summary>
        [Fact]
        public void HideRequestSummaryTest()
        {
            // TODO unit test for the property 'HideRequestSummary'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }
        /// <summary>
        /// Test the property 'LoadDepartmentFromUps'
        /// </summary>
        [Fact]
        public void LoadDepartmentFromUpsTest()
        {
            // TODO unit test for the property 'LoadDepartmentFromUps'
        }
        /// <summary>
        /// Test the property 'Departments'
        /// </summary>
        [Fact]
        public void DepartmentsTest()
        {
            // TODO unit test for the property 'Departments'
        }
        /// <summary>
        /// Test the property 'ServiceContact'
        /// </summary>
        [Fact]
        public void ServiceContactTest()
        {
            // TODO unit test for the property 'ServiceContact'
        }
        /// <summary>
        /// Test the property 'ServiceAdminContact'
        /// </summary>
        [Fact]
        public void ServiceAdminContactTest()
        {
            // TODO unit test for the property 'ServiceAdminContact'
        }
        /// <summary>
        /// Test the property 'ApproversContainManagerRole'
        /// </summary>
        [Fact]
        public void ApproversContainManagerRoleTest()
        {
            // TODO unit test for the property 'ApproversContainManagerRole'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ShowServiceInCatalog'
        /// </summary>
        [Fact]
        public void ShowServiceInCatalogTest()
        {
            // TODO unit test for the property 'ShowServiceInCatalog'
        }
        /// <summary>
        /// Test the property 'CustomActivity'
        /// </summary>
        [Fact]
        public void CustomActivityTest()
        {
            // TODO unit test for the property 'CustomActivity'
        }
        /// <summary>
        /// Test the property 'ApprovalProcessId'
        /// </summary>
        [Fact]
        public void ApprovalProcessIdTest()
        {
            // TODO unit test for the property 'ApprovalProcessId'
        }
        /// <summary>
        /// Test the property 'LanguageId'
        /// </summary>
        [Fact]
        public void LanguageIdTest()
        {
            // TODO unit test for the property 'LanguageId'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }

    }

}
