/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing GroupUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupUser
        //private GroupUser instance;

        public GroupUserTests()
        {
            // TODO uncomment below to create an instance of GroupUser
            //instance = new GroupUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupUser
        /// </summary>
        [Fact]
        public void GroupUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupUser
            //Assert.IsInstanceOfType<GroupUser> (instance, "variable 'instance' is a GroupUser");
        }


        /// <summary>
        /// Test the property 'IsEnforce'
        /// </summary>
        [Fact]
        public void IsEnforceTest()
        {
            // TODO unit test for the property 'IsEnforce'
        }
        /// <summary>
        /// Test the property 'IsHide'
        /// </summary>
        [Fact]
        public void IsHideTest()
        {
            // TODO unit test for the property 'IsHide'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LoginName'
        /// </summary>
        [Fact]
        public void LoginNameTest()
        {
            // TODO unit test for the property 'LoginName'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'IsGroup'
        /// </summary>
        [Fact]
        public void IsGroupTest()
        {
            // TODO unit test for the property 'IsGroup'
        }
        /// <summary>
        /// Test the property 'JobTitle'
        /// </summary>
        [Fact]
        public void JobTitleTest()
        {
            // TODO unit test for the property 'JobTitle'
        }
        /// <summary>
        /// Test the property 'PhysicalDeliveryOfficeName'
        /// </summary>
        [Fact]
        public void PhysicalDeliveryOfficeNameTest()
        {
            // TODO unit test for the property 'PhysicalDeliveryOfficeName'
        }

    }

}
