/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing MetadataActionLockItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetadataActionLockItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetadataActionLockItem
        //private MetadataActionLockItem instance;

        public MetadataActionLockItemTests()
        {
            // TODO uncomment below to create an instance of MetadataActionLockItem
            //instance = new MetadataActionLockItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetadataActionLockItem
        /// </summary>
        [Fact]
        public void MetadataActionLockItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MetadataActionLockItem
            //Assert.IsInstanceOfType<MetadataActionLockItem> (instance, "variable 'instance' is a MetadataActionLockItem");
        }


        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }
        /// <summary>
        /// Test the property 'MetadataActionInstanceId'
        /// </summary>
        [Fact]
        public void MetadataActionInstanceIdTest()
        {
            // TODO unit test for the property 'MetadataActionInstanceId'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'IsEnabledText'
        /// </summary>
        [Fact]
        public void IsEnabledTextTest()
        {
            // TODO unit test for the property 'IsEnabledText'
        }

    }

}
