/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing PermissionActionItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PermissionActionItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PermissionActionItem
        //private PermissionActionItem instance;

        public PermissionActionItemTests()
        {
            // TODO uncomment below to create an instance of PermissionActionItem
            //instance = new PermissionActionItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PermissionActionItem
        /// </summary>
        [Fact]
        public void PermissionActionItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PermissionActionItem
            //Assert.IsInstanceOfType<PermissionActionItem> (instance, "variable 'instance' is a PermissionActionItem");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IdInSharepoint'
        /// </summary>
        [Fact]
        public void IdInSharepointTest()
        {
            // TODO unit test for the property 'IdInSharepoint'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'AccountTypeDescription'
        /// </summary>
        [Fact]
        public void AccountTypeDescriptionTest()
        {
            // TODO unit test for the property 'AccountTypeDescription'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'LevelDescription'
        /// </summary>
        [Fact]
        public void LevelDescriptionTest()
        {
            // TODO unit test for the property 'LevelDescription'
        }
        /// <summary>
        /// Test the property 'MemberOf'
        /// </summary>
        [Fact]
        public void MemberOfTest()
        {
            // TODO unit test for the property 'MemberOf'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'PermissionLevel'
        /// </summary>
        [Fact]
        public void PermissionLevelTest()
        {
            // TODO unit test for the property 'PermissionLevel'
        }
        /// <summary>
        /// Test the property 'SharePointGroup'
        /// </summary>
        [Fact]
        public void SharePointGroupTest()
        {
            // TODO unit test for the property 'SharePointGroup'
        }
        /// <summary>
        /// Test the property 'TitleName'
        /// </summary>
        [Fact]
        public void TitleNameTest()
        {
            // TODO unit test for the property 'TitleName'
        }
        /// <summary>
        /// Test the property 'UserOrGroup'
        /// </summary>
        [Fact]
        public void UserOrGroupTest()
        {
            // TODO unit test for the property 'UserOrGroup'
        }
        /// <summary>
        /// Test the property 'MemberId'
        /// </summary>
        [Fact]
        public void MemberIdTest()
        {
            // TODO unit test for the property 'MemberId'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'ParentAccountType'
        /// </summary>
        [Fact]
        public void ParentAccountTypeTest()
        {
            // TODO unit test for the property 'ParentAccountType'
        }
        /// <summary>
        /// Test the property 'ActionType'
        /// </summary>
        [Fact]
        public void ActionTypeTest()
        {
            // TODO unit test for the property 'ActionType'
        }
        /// <summary>
        /// Test the property 'AccessType'
        /// </summary>
        [Fact]
        public void AccessTypeTest()
        {
            // TODO unit test for the property 'AccessType'
        }
        /// <summary>
        /// Test the property 'AccessTypeDescription'
        /// </summary>
        [Fact]
        public void AccessTypeDescriptionTest()
        {
            // TODO unit test for the property 'AccessTypeDescription'
        }
        /// <summary>
        /// Test the property 'IsSiteAdministrator'
        /// </summary>
        [Fact]
        public void IsSiteAdministratorTest()
        {
            // TODO unit test for the property 'IsSiteAdministrator'
        }

    }

}
