/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing RequestGroupWithPermissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestGroupWithPermissionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestGroupWithPermissions
        //private RequestGroupWithPermissions instance;

        public RequestGroupWithPermissionsTests()
        {
            // TODO uncomment below to create an instance of RequestGroupWithPermissions
            //instance = new RequestGroupWithPermissions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestGroupWithPermissions
        /// </summary>
        [Fact]
        public void RequestGroupWithPermissionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestGroupWithPermissions
            //Assert.IsInstanceOfType<RequestGroupWithPermissions> (instance, "variable 'instance' is a RequestGroupWithPermissions");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
        /// <summary>
        /// Test the property 'PermissionLevels'
        /// </summary>
        [Fact]
        public void PermissionLevelsTest()
        {
            // TODO unit test for the property 'PermissionLevels'
        }
        /// <summary>
        /// Test the property 'GroupOwner'
        /// </summary>
        [Fact]
        public void GroupOwnerTest()
        {
            // TODO unit test for the property 'GroupOwner'
        }
        /// <summary>
        /// Test the property 'GroupOwnerType'
        /// </summary>
        [Fact]
        public void GroupOwnerTypeTest()
        {
            // TODO unit test for the property 'GroupOwnerType'
        }
        /// <summary>
        /// Test the property 'BuildInGroupType'
        /// </summary>
        [Fact]
        public void BuildInGroupTypeTest()
        {
            // TODO unit test for the property 'BuildInGroupType'
        }

    }

}
