/* 
 * Cloud Governance Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloud.Governance.NewSdk.Api;
using Cloud.Governance.NewSdk.Model;
using Cloud.Governance.NewSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloud.Governance.NewSdk.Test
{
    /// <summary>
    ///  Class for testing TreeNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TreeNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TreeNode
        //private TreeNode instance;

        public TreeNodeTests()
        {
            // TODO uncomment below to create an instance of TreeNode
            //instance = new TreeNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TreeNode
        /// </summary>
        [Fact]
        public void TreeNodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TreeNode
            //Assert.IsInstanceOfType<TreeNode> (instance, "variable 'instance' is a TreeNode");
        }


        /// <summary>
        /// Test the property 'WebApplicationId'
        /// </summary>
        [Fact]
        public void WebApplicationIdTest()
        {
            // TODO unit test for the property 'WebApplicationId'
        }
        /// <summary>
        /// Test the property 'WebApplicationUri'
        /// </summary>
        [Fact]
        public void WebApplicationUriTest()
        {
            // TODO unit test for the property 'WebApplicationUri'
        }
        /// <summary>
        /// Test the property 'SiteCollectionId'
        /// </summary>
        [Fact]
        public void SiteCollectionIdTest()
        {
            // TODO unit test for the property 'SiteCollectionId'
        }
        /// <summary>
        /// Test the property 'SiteCollectionUrl'
        /// </summary>
        [Fact]
        public void SiteCollectionUrlTest()
        {
            // TODO unit test for the property 'SiteCollectionUrl'
        }
        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
        /// <summary>
        /// Test the property 'NodeId'
        /// </summary>
        [Fact]
        public void NodeIdTest()
        {
            // TODO unit test for the property 'NodeId'
        }
        /// <summary>
        /// Test the property 'StartIndex'
        /// </summary>
        [Fact]
        public void StartIndexTest()
        {
            // TODO unit test for the property 'StartIndex'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }
        /// <summary>
        /// Test the property 'FullCount'
        /// </summary>
        [Fact]
        public void FullCountTest()
        {
            // TODO unit test for the property 'FullCount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'ManagedPath'
        /// </summary>
        [Fact]
        public void ManagedPathTest()
        {
            // TODO unit test for the property 'ManagedPath'
        }
        /// <summary>
        /// Test the property 'AgentID'
        /// </summary>
        [Fact]
        public void AgentIDTest()
        {
            // TODO unit test for the property 'AgentID'
        }
        /// <summary>
        /// Test the property 'FullPath'
        /// </summary>
        [Fact]
        public void FullPathTest()
        {
            // TODO unit test for the property 'FullPath'
        }
        /// <summary>
        /// Test the property 'FarmName'
        /// </summary>
        [Fact]
        public void FarmNameTest()
        {
            // TODO unit test for the property 'FarmName'
        }
        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Fact]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }
        /// <summary>
        /// Test the property 'FarmID'
        /// </summary>
        [Fact]
        public void FarmIDTest()
        {
            // TODO unit test for the property 'FarmID'
        }
        /// <summary>
        /// Test the property 'ParentID'
        /// </summary>
        [Fact]
        public void ParentIDTest()
        {
            // TODO unit test for the property 'ParentID'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Fact]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SpObjectID'
        /// </summary>
        [Fact]
        public void SpObjectIDTest()
        {
            // TODO unit test for the property 'SpObjectID'
        }
        /// <summary>
        /// Test the property 'ParentSPObjectID'
        /// </summary>
        [Fact]
        public void ParentSPObjectIDTest()
        {
            // TODO unit test for the property 'ParentSPObjectID'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LoadManagedPath'
        /// </summary>
        [Fact]
        public void LoadManagedPathTest()
        {
            // TODO unit test for the property 'LoadManagedPath'
        }
        /// <summary>
        /// Test the property 'LoadChildrenFromDB'
        /// </summary>
        [Fact]
        public void LoadChildrenFromDBTest()
        {
            // TODO unit test for the property 'LoadChildrenFromDB'
        }
        /// <summary>
        /// Test the property 'LoadedPageCount'
        /// </summary>
        [Fact]
        public void LoadedPageCountTest()
        {
            // TODO unit test for the property 'LoadedPageCount'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'SelectedChildren'
        /// </summary>
        [Fact]
        public void SelectedChildrenTest()
        {
            // TODO unit test for the property 'SelectedChildren'
        }
        /// <summary>
        /// Test the property 'FilterUrls'
        /// </summary>
        [Fact]
        public void FilterUrlsTest()
        {
            // TODO unit test for the property 'FilterUrls'
        }
        /// <summary>
        /// Test the property 'FilterType'
        /// </summary>
        [Fact]
        public void FilterTypeTest()
        {
            // TODO unit test for the property 'FilterType'
        }
        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Fact]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }
        /// <summary>
        /// Test the property 'SelectedWebAppIdSubSiteProvServ'
        /// </summary>
        [Fact]
        public void SelectedWebAppIdSubSiteProvServTest()
        {
            // TODO unit test for the property 'SelectedWebAppIdSubSiteProvServ'
        }
        /// <summary>
        /// Test the property 'SelectedSiteCollIdsSubSiteProvServ'
        /// </summary>
        [Fact]
        public void SelectedSiteCollIdsSubSiteProvServTest()
        {
            // TODO unit test for the property 'SelectedSiteCollIdsSubSiteProvServ'
        }
        /// <summary>
        /// Test the property 'ChildrenType'
        /// </summary>
        [Fact]
        public void ChildrenTypeTest()
        {
            // TODO unit test for the property 'ChildrenType'
        }
        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Fact]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }
        /// <summary>
        /// Test the property 'ServerRelativeUrl'
        /// </summary>
        [Fact]
        public void ServerRelativeUrlTest()
        {
            // TODO unit test for the property 'ServerRelativeUrl'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
