// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * None=0, Edit=1, ReadOnly=2, </br>Hide=3
 * @export
 * @enum {string}
 */
export enum AutoPopulateUrlAssignBy {
    None = 'None',
    Edit = 'Edit',
    ReadOnly = 'ReadOnly',
    Hide = 'Hide'
}

export function AutoPopulateUrlAssignByFromJSON(json: any): AutoPopulateUrlAssignBy {
    return AutoPopulateUrlAssignByFromJSONTyped(json, false);
}

export function AutoPopulateUrlAssignByFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoPopulateUrlAssignBy {
    return json as AutoPopulateUrlAssignBy;
}

export function AutoPopulateUrlAssignByToJSON(value?: AutoPopulateUrlAssignBy): any {
    return value as any;
}

