// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiDurationType,
    ApiDurationTypeFromJSON,
    ApiDurationTypeFromJSONTyped,
    ApiDurationTypeToJSON,
    CommentsParam,
    CommentsParamFromJSON,
    CommentsParamFromJSONTyped,
    CommentsParamToJSON,
    LifecycleAction,
    LifecycleActionFromJSON,
    LifecycleActionFromJSONTyped,
    LifecycleActionToJSON,
    RequestMetadata,
    RequestMetadataFromJSON,
    RequestMetadataFromJSONTyped,
    RequestMetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface AutoTaskExtendRequest
 */
export interface AutoTaskExtendRequest {
    /**
     * 
     * @type {LifecycleAction}
     * @memberof AutoTaskExtendRequest
     */
    action?: LifecycleAction;
    /**
     * 
     * @type {number}
     * @memberof AutoTaskExtendRequest
     */
    extendDuration?: number;
    /**
     * 
     * @type {ApiDurationType}
     * @memberof AutoTaskExtendRequest
     */
    extendDurationType?: ApiDurationType;
    /**
     * 
     * @type {string}
     * @memberof AutoTaskExtendRequest
     */
    taskId?: string;
    /**
     * 
     * @type {Array<RequestMetadata>}
     * @memberof AutoTaskExtendRequest
     */
    metadatas?: Array<RequestMetadata> | null;
    /**
     * 
     * @type {CommentsParam}
     * @memberof AutoTaskExtendRequest
     */
    comments?: CommentsParam;
}

export function AutoTaskExtendRequestFromJSON(json: any): AutoTaskExtendRequest {
    return AutoTaskExtendRequestFromJSONTyped(json, false);
}

export function AutoTaskExtendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoTaskExtendRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : LifecycleActionFromJSON(json['action']),
        'extendDuration': !exists(json, 'extendDuration') ? undefined : json['extendDuration'],
        'extendDurationType': !exists(json, 'extendDurationType') ? undefined : ApiDurationTypeFromJSON(json['extendDurationType']),
        'taskId': !exists(json, 'taskId') ? undefined : json['taskId'],
        'metadatas': !exists(json, 'metadatas') ? undefined : (json['metadatas'] as Array<any>).map(RequestMetadataFromJSON),
        'comments': !exists(json, 'comments') ? undefined : CommentsParamFromJSON(json['comments']),
    };
}

export function AutoTaskExtendRequestToJSON(value?: AutoTaskExtendRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': LifecycleActionToJSON(value.action),
        'extendDuration': value.extendDuration,
        'extendDurationType': ApiDurationTypeToJSON(value.extendDurationType),
        'taskId': value.taskId,
        'metadatas': value.metadatas == null ? undefined : (value.metadatas as Array<any>).map(RequestMetadataToJSON),
        'comments': CommentsParamToJSON(value.comments),
    };
}


