// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RequestMetadata,
    RequestMetadataFromJSON,
    RequestMetadataFromJSONTyped,
    RequestMetadataToJSON,
    RequestStatus,
    RequestStatusFromJSON,
    RequestStatusFromJSONTyped,
    RequestStatusToJSON,
    ServiceType,
    ServiceTypeFromJSON,
    ServiceTypeFromJSONTyped,
    ServiceTypeToJSON,
    SiteLifecycleActionType,
    SiteLifecycleActionTypeFromJSON,
    SiteLifecycleActionTypeFromJSONTyped,
    SiteLifecycleActionTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ChangeSiteQuotaRequest
 */
export interface ChangeSiteQuotaRequest {
    /**
     * 
     * @type {number}
     * @memberof ChangeSiteQuotaRequest
     */
    quotaSize?: number;
    /**
     * 
     * @type {SiteLifecycleActionType}
     * @memberof ChangeSiteQuotaRequest
     */
    action?: SiteLifecycleActionType;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    readonly actionDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    siteId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    siteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    serviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    notesToApprovers?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    questionnaireId?: string | null;
    /**
     * 
     * @type {Array<RequestMetadata>}
     * @memberof ChangeSiteQuotaRequest
     */
    metadatas?: Array<RequestMetadata> | null;
    /**
     * 
     * @type {number}
     * @memberof ChangeSiteQuotaRequest
     */
    ticketNumber?: number | null;
    /**
     * 
     * @type {ServiceType}
     * @memberof ChangeSiteQuotaRequest
     */
    type?: ServiceType;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    readonly typeDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    requester?: string | null;
    /**
     * 
     * @type {RequestStatus}
     * @memberof ChangeSiteQuotaRequest
     */
    status?: RequestStatus;
    /**
     * 
     * @type {number}
     * @memberof ChangeSiteQuotaRequest
     */
    readonly progressStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    readonly progressStatusDescription?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ChangeSiteQuotaRequest
     */
    submittedTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ChangeSiteQuotaRequest
     */
    lastUpdated?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ChangeSiteQuotaRequest
     */
    createdTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    assignTo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeSiteQuotaRequest
     */
    fullPath?: string | null;
}

export function ChangeSiteQuotaRequestFromJSON(json: any): ChangeSiteQuotaRequest {
    return ChangeSiteQuotaRequestFromJSONTyped(json, false);
}

export function ChangeSiteQuotaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeSiteQuotaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quotaSize': !exists(json, 'quotaSize') ? undefined : json['quotaSize'],
        'action': !exists(json, 'action') ? undefined : SiteLifecycleActionTypeFromJSON(json['action']),
        'actionDescription': !exists(json, 'actionDescription') ? undefined : json['actionDescription'],
        'siteId': !exists(json, 'siteId') ? undefined : json['siteId'],
        'siteUrl': !exists(json, 'siteUrl') ? undefined : json['siteUrl'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'serviceId': !exists(json, 'serviceId') ? undefined : json['serviceId'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'notesToApprovers': !exists(json, 'notesToApprovers') ? undefined : json['notesToApprovers'],
        'questionnaireId': !exists(json, 'questionnaireId') ? undefined : json['questionnaireId'],
        'metadatas': !exists(json, 'metadatas') ? undefined : (json['metadatas'] as Array<any>).map(RequestMetadataFromJSON),
        'ticketNumber': !exists(json, 'ticketNumber') ? undefined : json['ticketNumber'],
        'type': !exists(json, 'type') ? undefined : ServiceTypeFromJSON(json['type']),
        'typeDescription': !exists(json, 'typeDescription') ? undefined : json['typeDescription'],
        'requester': !exists(json, 'requester') ? undefined : json['requester'],
        'status': !exists(json, 'status') ? undefined : RequestStatusFromJSON(json['status']),
        'progressStatus': !exists(json, 'progressStatus') ? undefined : json['progressStatus'],
        'progressStatusDescription': !exists(json, 'progressStatusDescription') ? undefined : json['progressStatusDescription'],
        'submittedTime': !exists(json, 'submittedTime') ? undefined : new Date(json['submittedTime']),
        'lastUpdated': !exists(json, 'lastUpdated') ? undefined : new Date(json['lastUpdated']),
        'createdTime': !exists(json, 'createdTime') ? undefined : new Date(json['createdTime']),
        'assignTo': !exists(json, 'assignTo') ? undefined : json['assignTo'],
        'fullPath': !exists(json, 'fullPath') ? undefined : json['fullPath'],
    };
}

export function ChangeSiteQuotaRequestToJSON(value?: ChangeSiteQuotaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quotaSize': value.quotaSize,
        'action': SiteLifecycleActionTypeToJSON(value.action),
        'siteId': value.siteId,
        'siteUrl': value.siteUrl,
        'id': value.id,
        'serviceId': value.serviceId,
        'department': value.department,
        'summary': value.summary,
        'notesToApprovers': value.notesToApprovers,
        'questionnaireId': value.questionnaireId,
        'metadatas': value.metadatas == null ? undefined : (value.metadatas as Array<any>).map(RequestMetadataToJSON),
        'ticketNumber': value.ticketNumber,
        'type': ServiceTypeToJSON(value.type),
        'requester': value.requester,
        'status': RequestStatusToJSON(value.status),
        'submittedTime': value.submittedTime == null ? undefined : value.submittedTime.toISOString(),
        'lastUpdated': value.lastUpdated == null ? undefined : value.lastUpdated.toISOString(),
        'createdTime': value.createdTime == null ? undefined : value.createdTime.toISOString(),
        'assignTo': value.assignTo,
        'fullPath': value.fullPath,
    };
}


