// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * None=0, SingleLineText=1, MultiLineText=2, </br>YesOrNo=3, Choices=4, PeoplePickerValue=5, </br>Terms=6, Hyperlink=7, UserProfileService=8, </br>AzureADProperty=9
 * @export
 * @enum {string}
 */
export enum MetadataFieldType {
    None = 'None',
    SingleLineText = 'SingleLineText',
    MultiLineText = 'MultiLineText',
    YesOrNo = 'YesOrNo',
    Choices = 'Choices',
    PeoplePickerValue = 'PeoplePickerValue',
    Terms = 'Terms',
    Hyperlink = 'Hyperlink',
    UserProfileService = 'UserProfileService',
    AzureADProperty = 'AzureADProperty'
}

export function MetadataFieldTypeFromJSON(json: any): MetadataFieldType {
    return MetadataFieldTypeFromJSONTyped(json, false);
}

export function MetadataFieldTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataFieldType {
    return json as MetadataFieldType;
}

export function MetadataFieldTypeToJSON(value?: MetadataFieldType): any {
    return value as any;
}

