// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiUser,
    ApiUserFromJSON,
    ApiUserFromJSONTyped,
    ApiUserToJSON,
    AutoImportPhase,
    AutoImportPhaseFromJSON,
    AutoImportPhaseFromJSONTyped,
    AutoImportPhaseToJSON,
    MySiteType,
    MySiteTypeFromJSON,
    MySiteTypeFromJSONTyped,
    MySiteTypeToJSON,
    RequestMetadata,
    RequestMetadataFromJSON,
    RequestMetadataFromJSONTyped,
    RequestMetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface MySite
 */
export interface MySite {
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    fullUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MySite
     */
    size?: number | null;
    /**
     * 
     * @type {MySiteType}
     * @memberof MySite
     */
    type?: MySiteType;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    readonly mySiteType?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MySite
     */
    createdTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    storageUsed?: string | null;
    /**
     * 
     * @type {ApiUser}
     * @memberof MySite
     */
    primaryAdministrator?: ApiUser;
    /**
     * 
     * @type {Array<ApiUser>}
     * @memberof MySite
     */
    additionalAdministrator?: Array<ApiUser> | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    preferredDataLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    readonly preferredDataLocationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    id?: string;
    /**
     * 
     * @type {AutoImportPhase}
     * @memberof MySite
     */
    phase?: AutoImportPhase;
    /**
     * 
     * @type {Date}
     * @memberof MySite
     */
    phaseStartTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    readonly phaseDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    autoImportProfileId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    autoImportProfileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    policyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MySite
     */
    policyDescription?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MySite
     */
    isCurrentRenewer?: boolean;
    /**
     * 
     * @type {Array<ApiUser>}
     * @memberof MySite
     */
    phaseAssignees?: Array<ApiUser> | null;
    /**
     * 
     * @type {Array<RequestMetadata>}
     * @memberof MySite
     */
    metadatas?: Array<RequestMetadata> | null;
    /**
     * 
     * @type {ApiUser}
     * @memberof MySite
     */
    primaryContact?: ApiUser;
    /**
     * 
     * @type {ApiUser}
     * @memberof MySite
     */
    secondaryContact?: ApiUser;
}

export function MySiteFromJSON(json: any): MySite {
    return MySiteFromJSONTyped(json, false);
}

export function MySiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): MySite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullUrl': !exists(json, 'fullUrl') ? undefined : json['fullUrl'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'type': !exists(json, 'type') ? undefined : MySiteTypeFromJSON(json['type']),
        'mySiteType': !exists(json, 'mySiteType') ? undefined : json['mySiteType'],
        'createdTime': !exists(json, 'createdTime') ? undefined : new Date(json['createdTime']),
        'storageUsed': !exists(json, 'storageUsed') ? undefined : json['storageUsed'],
        'primaryAdministrator': !exists(json, 'primaryAdministrator') ? undefined : ApiUserFromJSON(json['primaryAdministrator']),
        'additionalAdministrator': !exists(json, 'additionalAdministrator') ? undefined : (json['additionalAdministrator'] as Array<any>).map(ApiUserFromJSON),
        'preferredDataLocation': !exists(json, 'preferredDataLocation') ? undefined : json['preferredDataLocation'],
        'preferredDataLocationName': !exists(json, 'preferredDataLocationName') ? undefined : json['preferredDataLocationName'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'phase': !exists(json, 'phase') ? undefined : AutoImportPhaseFromJSON(json['phase']),
        'phaseStartTime': !exists(json, 'phaseStartTime') ? undefined : new Date(json['phaseStartTime']),
        'phaseDescription': !exists(json, 'phaseDescription') ? undefined : json['phaseDescription'],
        'autoImportProfileId': !exists(json, 'autoImportProfileId') ? undefined : json['autoImportProfileId'],
        'autoImportProfileName': !exists(json, 'autoImportProfileName') ? undefined : json['autoImportProfileName'],
        'policyName': !exists(json, 'policyName') ? undefined : json['policyName'],
        'policyDescription': !exists(json, 'policyDescription') ? undefined : json['policyDescription'],
        'isCurrentRenewer': !exists(json, 'isCurrentRenewer') ? undefined : json['isCurrentRenewer'],
        'phaseAssignees': !exists(json, 'phaseAssignees') ? undefined : (json['phaseAssignees'] as Array<any>).map(ApiUserFromJSON),
        'metadatas': !exists(json, 'metadatas') ? undefined : (json['metadatas'] as Array<any>).map(RequestMetadataFromJSON),
        'primaryContact': !exists(json, 'primaryContact') ? undefined : ApiUserFromJSON(json['primaryContact']),
        'secondaryContact': !exists(json, 'secondaryContact') ? undefined : ApiUserFromJSON(json['secondaryContact']),
    };
}

export function MySiteToJSON(value?: MySite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullUrl': value.fullUrl,
        'title': value.title,
        'department': value.department,
        'description': value.description,
        'size': value.size,
        'type': MySiteTypeToJSON(value.type),
        'createdTime': value.createdTime == null ? undefined : value.createdTime.toISOString(),
        'storageUsed': value.storageUsed,
        'primaryAdministrator': ApiUserToJSON(value.primaryAdministrator),
        'additionalAdministrator': value.additionalAdministrator == null ? undefined : (value.additionalAdministrator as Array<any>).map(ApiUserToJSON),
        'preferredDataLocation': value.preferredDataLocation,
        'id': value.id,
        'phase': AutoImportPhaseToJSON(value.phase),
        'phaseStartTime': value.phaseStartTime == null ? undefined : value.phaseStartTime.toISOString(),
        'autoImportProfileId': value.autoImportProfileId,
        'autoImportProfileName': value.autoImportProfileName,
        'policyName': value.policyName,
        'policyDescription': value.policyDescription,
        'isCurrentRenewer': value.isCurrentRenewer,
        'phaseAssignees': value.phaseAssignees == null ? undefined : (value.phaseAssignees as Array<any>).map(ApiUserToJSON),
        'metadatas': value.metadatas == null ? undefined : (value.metadatas as Array<any>).map(RequestMetadataToJSON),
        'primaryContact': ApiUserToJSON(value.primaryContact),
        'secondaryContact': ApiUserToJSON(value.secondaryContact),
    };
}


