// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GuidModel,
    GuidModelFromJSON,
    GuidModelFromJSONTyped,
    GuidModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface TermsMetadataSettings
 */
export interface TermsMetadataSettings {
    /**
     * 
     * @type {boolean}
     * @memberof TermsMetadataSettings
     */
    allowMultiple?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TermsMetadataSettings
     */
    adminCenter?: string | null;
    /**
     * 
     * @type {Array<GuidModel>}
     * @memberof TermsMetadataSettings
     */
    value?: Array<GuidModel> | null;
    /**
     * 
     * @type {GuidModel}
     * @memberof TermsMetadataSettings
     */
    termStore?: GuidModel;
    /**
     * 
     * @type {GuidModel}
     * @memberof TermsMetadataSettings
     */
    termGroup?: GuidModel;
    /**
     * 
     * @type {GuidModel}
     * @memberof TermsMetadataSettings
     */
    termSet?: GuidModel;
    /**
     * 
     * @type {GuidModel}
     * @memberof TermsMetadataSettings
     */
    scope?: GuidModel;
}

export function TermsMetadataSettingsFromJSON(json: any): TermsMetadataSettings {
    return TermsMetadataSettingsFromJSONTyped(json, false);
}

export function TermsMetadataSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TermsMetadataSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'allowMultiple': !exists(json, 'allowMultiple') ? undefined : json['allowMultiple'],
        'adminCenter': !exists(json, 'adminCenter') ? undefined : json['adminCenter'],
        'value': !exists(json, 'value') ? undefined : (json['value'] as Array<any>).map(GuidModelFromJSON),
        'termStore': !exists(json, 'termStore') ? undefined : GuidModelFromJSON(json['termStore']),
        'termGroup': !exists(json, 'termGroup') ? undefined : GuidModelFromJSON(json['termGroup']),
        'termSet': !exists(json, 'termSet') ? undefined : GuidModelFromJSON(json['termSet']),
        'scope': !exists(json, 'scope') ? undefined : GuidModelFromJSON(json['scope']),
    };
}

export function TermsMetadataSettingsToJSON(value?: TermsMetadataSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'allowMultiple': value.allowMultiple,
        'adminCenter': value.adminCenter,
        'value': value.value == null ? undefined : (value.value as Array<any>).map(GuidModelToJSON),
        'termStore': GuidModelToJSON(value.termStore),
        'termGroup': GuidModelToJSON(value.termGroup),
        'termSet': GuidModelToJSON(value.termSet),
        'scope': GuidModelToJSON(value.scope),
    };
}


