// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlockSiteSetting
 */
export interface UnlockSiteSetting {
    /**
     * 
     * @type {boolean}
     * @memberof UnlockSiteSetting
     */
    isExpired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UnlockSiteSetting
     */
    isExtendEnabled?: boolean;
}

export function UnlockSiteSettingFromJSON(json: any): UnlockSiteSetting {
    return UnlockSiteSettingFromJSONTyped(json, false);
}

export function UnlockSiteSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlockSiteSetting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isExpired': !exists(json, 'isExpired') ? undefined : json['isExpired'],
        'isExtendEnabled': !exists(json, 'isExtendEnabled') ? undefined : json['isExtendEnabled'],
    };
}

export function UnlockSiteSettingToJSON(value?: UnlockSiteSetting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isExpired': value.isExpired,
        'isExtendEnabled': value.isExtendEnabled,
    };
}


