// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiUser,
    ApiUserFromJSON,
    ApiUserFromJSONTyped,
    ApiUserToJSON,
    AssignBy,
    AssignByFromJSON,
    AssignByFromJSONTyped,
    AssignByToJSON,
    CommonStatus,
    CommonStatusFromJSON,
    CommonStatusFromJSONTyped,
    CommonStatusToJSON,
    CustomActivityInfo,
    CustomActivityInfoFromJSON,
    CustomActivityInfoFromJSONTyped,
    CustomActivityInfoToJSON,
    CustomMetadata,
    CustomMetadataFromJSON,
    CustomMetadataFromJSONTyped,
    CustomMetadataToJSON,
    ServiceType,
    ServiceTypeFromJSON,
    ServiceTypeFromJSONTyped,
    ServiceTypeToJSON,
    WebLifecycleActionType,
    WebLifecycleActionTypeFromJSON,
    WebLifecycleActionTypeFromJSONTyped,
    WebLifecycleActionTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface WebLifecycleService
 */
export interface WebLifecycleService {
    /**
     * 
     * @type {WebLifecycleActionType}
     * @memberof WebLifecycleService
     */
    action?: WebLifecycleActionType;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    archiveContentProfile?: string | null;
    /**
     * 
     * @type {AssignBy}
     * @memberof WebLifecycleService
     */
    departmentAssignBy?: AssignBy;
    /**
     * 
     * @type {Array<CustomMetadata>}
     * @memberof WebLifecycleService
     */
    metadatas?: Array<CustomMetadata> | null;
    /**
     * 
     * @type {boolean}
     * @memberof WebLifecycleService
     */
    hideRequestSummary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    description?: string | null;
    /**
     * 
     * @type {ServiceType}
     * @memberof WebLifecycleService
     */
    type?: ServiceType;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    department?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof WebLifecycleService
     */
    loadDepartmentFromUps?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebLifecycleService
     */
    departments?: Array<string> | null;
    /**
     * 
     * @type {ApiUser}
     * @memberof WebLifecycleService
     */
    serviceContact?: ApiUser;
    /**
     * 
     * @type {ApiUser}
     * @memberof WebLifecycleService
     */
    serviceAdminContact?: ApiUser;
    /**
     * 
     * @type {boolean}
     * @memberof WebLifecycleService
     */
    approversContainManagerRole?: boolean;
    /**
     * 
     * @type {CommonStatus}
     * @memberof WebLifecycleService
     */
    status?: CommonStatus;
    /**
     * 
     * @type {boolean}
     * @memberof WebLifecycleService
     */
    showServiceInCatalog?: boolean;
    /**
     * 
     * @type {CustomActivityInfo}
     * @memberof WebLifecycleService
     */
    customActivity?: CustomActivityInfo;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    approvalProcessId?: string;
    /**
     * 
     * @type {number}
     * @memberof WebLifecycleService
     */
    languageId?: number;
    /**
     * 
     * @type {string}
     * @memberof WebLifecycleService
     */
    categoryId?: string | null;
}

export function WebLifecycleServiceFromJSON(json: any): WebLifecycleService {
    return WebLifecycleServiceFromJSONTyped(json, false);
}

export function WebLifecycleServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebLifecycleService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : WebLifecycleActionTypeFromJSON(json['action']),
        'archiveContentProfile': !exists(json, 'archiveContentProfile') ? undefined : json['archiveContentProfile'],
        'departmentAssignBy': !exists(json, 'departmentAssignBy') ? undefined : AssignByFromJSON(json['departmentAssignBy']),
        'metadatas': !exists(json, 'metadatas') ? undefined : (json['metadatas'] as Array<any>).map(CustomMetadataFromJSON),
        'hideRequestSummary': !exists(json, 'hideRequestSummary') ? undefined : json['hideRequestSummary'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : ServiceTypeFromJSON(json['type']),
        'department': !exists(json, 'department') ? undefined : json['department'],
        'loadDepartmentFromUps': !exists(json, 'loadDepartmentFromUps') ? undefined : json['loadDepartmentFromUps'],
        'departments': !exists(json, 'departments') ? undefined : json['departments'],
        'serviceContact': !exists(json, 'serviceContact') ? undefined : ApiUserFromJSON(json['serviceContact']),
        'serviceAdminContact': !exists(json, 'serviceAdminContact') ? undefined : ApiUserFromJSON(json['serviceAdminContact']),
        'approversContainManagerRole': !exists(json, 'approversContainManagerRole') ? undefined : json['approversContainManagerRole'],
        'status': !exists(json, 'status') ? undefined : CommonStatusFromJSON(json['status']),
        'showServiceInCatalog': !exists(json, 'showServiceInCatalog') ? undefined : json['showServiceInCatalog'],
        'customActivity': !exists(json, 'customActivity') ? undefined : CustomActivityInfoFromJSON(json['customActivity']),
        'approvalProcessId': !exists(json, 'approvalProcessId') ? undefined : json['approvalProcessId'],
        'languageId': !exists(json, 'languageId') ? undefined : json['languageId'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
    };
}

export function WebLifecycleServiceToJSON(value?: WebLifecycleService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': WebLifecycleActionTypeToJSON(value.action),
        'archiveContentProfile': value.archiveContentProfile,
        'departmentAssignBy': AssignByToJSON(value.departmentAssignBy),
        'metadatas': value.metadatas == null ? undefined : (value.metadatas as Array<any>).map(CustomMetadataToJSON),
        'hideRequestSummary': value.hideRequestSummary,
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'type': ServiceTypeToJSON(value.type),
        'department': value.department,
        'loadDepartmentFromUps': value.loadDepartmentFromUps,
        'departments': value.departments,
        'serviceContact': ApiUserToJSON(value.serviceContact),
        'serviceAdminContact': ApiUserToJSON(value.serviceAdminContact),
        'approversContainManagerRole': value.approversContainManagerRole,
        'status': CommonStatusToJSON(value.status),
        'showServiceInCatalog': value.showServiceInCatalog,
        'customActivity': CustomActivityInfoToJSON(value.customActivity),
        'approvalProcessId': value.approvalProcessId,
        'languageId': value.languageId,
        'categoryId': value.categoryId,
    };
}


