// tslint:disable
/**
 * Cloud Governance Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * None=0, Delete=1, Archive=2, </br>
 * @export
 * @enum {string}
 */
export enum WebLifecycleActionType {
    None = 'None',
    Delete = 'Delete',
    Archive = 'Archive'
}

export function WebLifecycleActionTypeFromJSON(json: any): WebLifecycleActionType {
    return WebLifecycleActionTypeFromJSONTyped(json, false);
}

export function WebLifecycleActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebLifecycleActionType {
    return json as WebLifecycleActionType;
}

export function WebLifecycleActionTypeToJSON(value?: WebLifecycleActionType): any {
    return value as any;
}

