#
# Cloud Governance Api
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SelectedNodes
No description available.

.PARAMETER UnCheckedNodesInfo
No description available.

.PARAMETER ChangeMethod
No description available.

.PARAMETER ChangeMethodAssignBy
No description available.

.PARAMETER EnableNotifyNewContact
No description available.

.PARAMETER NewContactNotifiedEmail
No description available.

.PARAMETER ScopeSettings
No description available.

.PARAMETER DepartmentAssignBy
No description available.

.PARAMETER Metadatas
No description available.

.PARAMETER HideRequestSummary
No description available.

.PARAMETER Id
No description available.

.PARAMETER Name
No description available.

.PARAMETER Description
No description available.

.PARAMETER Type
No description available.

.PARAMETER Department
No description available.

.PARAMETER LoadDepartmentFromUps
No description available.

.PARAMETER Departments
No description available.

.PARAMETER ServiceContact
No description available.

.PARAMETER ServiceAdminContact
No description available.

.PARAMETER ApproversContainManagerRole
No description available.

.PARAMETER Status
No description available.

.PARAMETER ShowServiceInCatalog
No description available.

.PARAMETER CustomActions
No description available.

.PARAMETER ApprovalProcessId
No description available.

.PARAMETER LanguageId
No description available.

.PARAMETER CategoryId
No description available.

.OUTPUTS

ChangeWebContactService<PSCustomObject>
#>

function New-ChangeWebContactService {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SelectedNodes},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UnCheckedNodesInfo},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ChangeMethod},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ChangeMethodAssignBy},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableNotifyNewContact},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${NewContactNotifiedEmail},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ScopeSettings},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DepartmentAssignBy},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Metadatas},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HideRequestSummary},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Id},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Type},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Department},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${LoadDepartmentFromUps},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Departments},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ServiceContact},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ServiceAdminContact},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ApproversContainManagerRole},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Status},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShowServiceInCatalog},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomActions},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ApprovalProcessId},
        [Parameter(Position = 24, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${LanguageId},
        [Parameter(Position = 25, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CategoryId}
    )

    Process {
        'Creating object: Cloud.Governance.Client => ChangeWebContactService' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "selectedNodes" = ${SelectedNodes}
            "unCheckedNodesInfo" = ${UnCheckedNodesInfo}
            "changeMethod" = ${ChangeMethod}
            "changeMethodAssignBy" = ${ChangeMethodAssignBy}
            "enableNotifyNewContact" = ${EnableNotifyNewContact}
            "newContactNotifiedEmail" = ${NewContactNotifiedEmail}
            "scopeSettings" = ${ScopeSettings}
            "departmentAssignBy" = ${DepartmentAssignBy}
            "metadatas" = ${Metadatas}
            "hideRequestSummary" = ${HideRequestSummary}
            "id" = ${Id}
            "name" = ${Name}
            "description" = ${Description}
            "type" = ${Type}
            "department" = ${Department}
            "loadDepartmentFromUps" = ${LoadDepartmentFromUps}
            "departments" = ${Departments}
            "serviceContact" = ${ServiceContact}
            "serviceAdminContact" = ${ServiceAdminContact}
            "approversContainManagerRole" = ${ApproversContainManagerRole}
            "status" = ${Status}
            "showServiceInCatalog" = ${ShowServiceInCatalog}
            "customActions" = ${CustomActions}
            "approvalProcessId" = ${ApprovalProcessId}
            "languageId" = ${LanguageId}
            "categoryId" = ${CategoryId}
        }

        return $PSO
    }
}
