#
# Cloud Governance Api
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER GroupSiteLink
No description available.

.PARAMETER GroupPlannerLink
No description available.

.PARAMETER GroupFilesLink
No description available.

.PARAMETER GroupConversationsLink
No description available.

.PARAMETER GroupNotebookLink
No description available.

.OUTPUTS

GroupLinks<PSCustomObject>
#>

function New-GroupLinks {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GroupSiteLink},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GroupPlannerLink},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GroupFilesLink},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GroupConversationsLink},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GroupNotebookLink}
    )

    Process {
        'Creating object: Cloud.Governance.Client => GroupLinks' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "groupSiteLink" = ${GroupSiteLink}
            "groupPlannerLink" = ${GroupPlannerLink}
            "groupFilesLink" = ${GroupFilesLink}
            "groupConversationsLink" = ${GroupConversationsLink}
            "groupNotebookLink" = ${GroupNotebookLink}
        }

        return $PSO
    }
}
