#
# Cloud Governance Api
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

DoNotMigrateTheItems=0, OverwriteIdenticalItemsInDestination=1, Append=2, </br>IgnoreDifferenceAndMoveItems=3

.OUTPUTS

ItemConflictResolutionType<PSCustomObject>
#>

function New-ItemConflictResolutionType {
    [CmdletBinding()]
    Param (
    )

    Process {
        'Creating object: Cloud.Governance.Client => ItemConflictResolutionType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
        }

        return $PSO
    }
}
