#
# Cloud Governance Api
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER EnableLockAsNoAccess
No description available.

.PARAMETER EnableLockAsReadonly
No description available.

.OUTPUTS

LockSiteSetting<PSCustomObject>
#>

function New-LockSiteSetting {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableLockAsNoAccess},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableLockAsReadonly}
    )

    Process {
        'Creating object: Cloud.Governance.Client => LockSiteSetting' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "enableLockAsNoAccess" = ${EnableLockAsNoAccess}
            "enableLockAsReadonly" = ${EnableLockAsReadonly}
        }

        return $PSO
    }
}
