#
# Cloud Governance Api
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER UserScopeSetting
No description available.

.PARAMETER SharePointGroupOptions
No description available.

.PARAMETER PermissionOptions
No description available.

.PARAMETER ScopeSettings
No description available.

.PARAMETER DepartmentAssignBy
No description available.

.PARAMETER Metadatas
No description available.

.PARAMETER HideRequestSummary
No description available.

.PARAMETER Id
No description available.

.PARAMETER Name
No description available.

.PARAMETER Description
No description available.

.PARAMETER Type
No description available.

.PARAMETER Department
No description available.

.PARAMETER LoadDepartmentFromUps
No description available.

.PARAMETER Departments
No description available.

.PARAMETER ServiceContact
No description available.

.PARAMETER ServiceAdminContact
No description available.

.PARAMETER ApproversContainManagerRole
No description available.

.PARAMETER Status
No description available.

.PARAMETER ShowServiceInCatalog
No description available.

.PARAMETER CustomActions
No description available.

.PARAMETER ApprovalProcessId
No description available.

.PARAMETER LanguageId
No description available.

.PARAMETER CategoryId
No description available.

.OUTPUTS

ManagePermissionService<PSCustomObject>
#>

function New-ManagePermissionService {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UserScopeSetting},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SharePointGroupOptions},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${PermissionOptions},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ScopeSettings},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DepartmentAssignBy},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Metadatas},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HideRequestSummary},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Id},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Type},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Department},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${LoadDepartmentFromUps},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Departments},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ServiceContact},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ServiceAdminContact},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ApproversContainManagerRole},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Status},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShowServiceInCatalog},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomActions},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ApprovalProcessId},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${LanguageId},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CategoryId}
    )

    Process {
        'Creating object: Cloud.Governance.Client => ManagePermissionService' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "userScopeSetting" = ${UserScopeSetting}
            "sharePointGroupOptions" = ${SharePointGroupOptions}
            "permissionOptions" = ${PermissionOptions}
            "scopeSettings" = ${ScopeSettings}
            "departmentAssignBy" = ${DepartmentAssignBy}
            "metadatas" = ${Metadatas}
            "hideRequestSummary" = ${HideRequestSummary}
            "id" = ${Id}
            "name" = ${Name}
            "description" = ${Description}
            "type" = ${Type}
            "department" = ${Department}
            "loadDepartmentFromUps" = ${LoadDepartmentFromUps}
            "departments" = ${Departments}
            "serviceContact" = ${ServiceContact}
            "serviceAdminContact" = ${ServiceAdminContact}
            "approversContainManagerRole" = ${ApproversContainManagerRole}
            "status" = ${Status}
            "showServiceInCatalog" = ${ShowServiceInCatalog}
            "customActions" = ${CustomActions}
            "approvalProcessId" = ${ApprovalProcessId}
            "languageId" = ${LanguageId}
            "categoryId" = ${CategoryId}
        }

        return $PSO
    }
}
