#
# Cloud Governance Api
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER EnableAddOrDeletedMetadata
No description available.

.PARAMETER ObjectId
No description available.

.PARAMETER ObjectName
No description available.

.PARAMETER IsAllowedReassign
No description available.

.PARAMETER ReportGeneratedTime
No description available.

.PARAMETER RequestSummary
No description available.

.OUTPUTS

MetadataRecertificationReportProperties<PSCustomObject>
#>

function New-MetadataRecertificationReportProperties {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${EnableAddOrDeletedMetadata},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ObjectId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ObjectName},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsAllowedReassign},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${ReportGeneratedTime},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RequestSummary}
    )

    Process {
        'Creating object: Cloud.Governance.Client => MetadataRecertificationReportProperties' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "enableAddOrDeletedMetadata" = ${EnableAddOrDeletedMetadata}
            "objectId" = ${ObjectId}
            "objectName" = ${ObjectName}
            "isAllowedReassign" = ${IsAllowedReassign}
            "reportGeneratedTime" = ${ReportGeneratedTime}
            "requestSummary" = ${RequestSummary}
        }

        return $PSO
    }
}
